In [ ]:
!nvidia-smi # Run this to see what GPU you have

Sat Nov 30 15:13:12 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

In [ ]:
pip install laion-clap

Requirement already satisfied: laion-clap in /usr/local/lib/python3.10/dist-packages (1.1.6)
Requirement already satisfied: numpy==1.23.5 in /usr/local/lib/python3.10/dist-packages (from laion-clap) (1.23.5)
Requirement already satisfied: soundfile in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.12.1)
Requirement already satisfied: librosa in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.10.2.post1)
Requirement already satisfied: torchlibrosa in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.1.0)
Requirement already satisfied: ftfy in /usr/local/lib/python3.10/dist-packages (from laion-clap) (6.3.1)
Requirement already satisfied: braceexpand in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.1.7)
Requirement already satisfied: webdataset in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.2.100)
Requirement already satisfied: wget in /usr/local/lib/python3.10/dist-packages (from laion-clap) (3.2)
Requirement already satisfied: wandb in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.18.7)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.43.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from laion-clap) (1.13.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from laion-clap) (1.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from laion-clap) (2.1.4)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from laion-clap) (3.11.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from laion-clap) (4.66.5)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from laion-clap) (2024.9.11)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (from laion-clap) (4.44.2)
Requirement already satisfied: progressbar in /usr/local/lib/python3.10/dist-packages (from laion-clap) (2.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from ftfy->laion-clap) (0.2.13)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (3.0.1)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (4.4.2)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (0.60.0)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (0.5.0.post1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (4.12.2)
Requirement already satisfied: lazy-loader>=0.1 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (1.0.8)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->laion-clap) (3.5.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.10/dist-packages (from soundfile->laion-clap) (1.17.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->laion-clap) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->laion-clap) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->laion-clap) (2024.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (0.24.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (0.19.1)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (3.1.43)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (4.3.6)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (3.20.3)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (5.9.5)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (2.19.0)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (1.3.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (71.0.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0->soundfile->laion-clap) (2.22)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from docker-pycreds>=0.4.0->wandb->laion-clap) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb->laion-clap) (4.0.11)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers->laion-clap) (2024.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->laion-clap) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->laion-clap) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->laion-clap) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->laion-clap) (2024.8.30)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb->laion-clap) (5.0.1)

In [ ]:
import numpy as np
import librosa
import torch
import laion_clap

# quantization
def int16_to_float32(x):
    return (x / 32767.0).astype(np.float32)


def float32_to_int16(x):
    x = np.clip(x, a_min=-1., a_max=1.)
    return (x * 32767.).astype(np.int16)

model = laion_clap.CLAP_Module(enable_fusion=False)
model.load_ckpt() # download the default pretrained checkpoint.

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:99: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.72k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

Load our best checkpoint in the paper.
Downloading laion_clap weight files...
Download completed!
Load Checkpoint...

/usr/local/lib/python3.10/dist-packages/laion_clap/clap_module/factory.py:54: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location=map_location)

logit_scale_a 	 Loaded
logit_scale_t 	 Loaded
audio_branch.spectrogram_extractor.stft.conv_real.weight 	 Loaded
audio_branch.spectrogram_extractor.stft.conv_imag.weight 	 Loaded
audio_branch.logmel_extractor.melW 	 Loaded
audio_branch.bn0.weight 	 Loaded
audio_branch.bn0.bias 	 Loaded
audio_branch.patch_embed.proj.weight 	 Loaded
audio_branch.patch_embed.proj.bias 	 Loaded
audio_branch.patch_embed.norm.weight 	 Loaded
audio_branch.patch_embed.norm.bias 	 Loaded
audio_branch.layers.0.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.0.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.0.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.0.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.0.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.0.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.0.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.0.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.0.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.0.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.0.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.0.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.0.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.0.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.0.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.0.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.0.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.0.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.0.downsample.reduction.weight 	 Loaded
audio_branch.layers.0.downsample.norm.weight 	 Loaded
audio_branch.layers.0.downsample.norm.bias 	 Loaded
audio_branch.layers.1.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.1.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.1.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.1.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.1.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.1.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.1.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.1.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.1.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.1.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.1.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.1.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.1.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.1.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.1.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.1.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.1.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.1.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.1.downsample.reduction.weight 	 Loaded
audio_branch.layers.1.downsample.norm.weight 	 Loaded
audio_branch.layers.1.downsample.norm.bias 	 Loaded
audio_branch.layers.2.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.2.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.2.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.2.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.2.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.2.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.2.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.2.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.2.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.2.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.3.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.3.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.3.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.3.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.3.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.3.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.3.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.3.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.3.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.4.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.4.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.4.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.4.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.4.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.4.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.4.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.4.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.4.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.5.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.5.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.5.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.5.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.5.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.5.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.5.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.5.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.5.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.downsample.reduction.weight 	 Loaded
audio_branch.layers.2.downsample.norm.weight 	 Loaded
audio_branch.layers.2.downsample.norm.bias 	 Loaded
audio_branch.layers.3.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.3.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.3.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.3.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.3.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.3.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.3.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.3.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.3.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.3.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.3.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.3.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.3.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.3.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.3.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.3.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.3.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.3.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.norm.weight 	 Loaded
audio_branch.norm.bias 	 Loaded
audio_branch.tscam_conv.weight 	 Loaded
audio_branch.tscam_conv.bias 	 Loaded
audio_branch.head.weight 	 Loaded
audio_branch.head.bias 	 Loaded
text_branch.embeddings.word_embeddings.weight 	 Loaded
text_branch.embeddings.position_embeddings.weight 	 Loaded
text_branch.embeddings.token_type_embeddings.weight 	 Loaded
text_branch.embeddings.LayerNorm.weight 	 Loaded
text_branch.embeddings.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.0.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.0.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.0.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.0.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.0.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.0.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.0.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.0.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.0.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.0.output.dense.weight 	 Loaded
text_branch.encoder.layer.0.output.dense.bias 	 Loaded
text_branch.encoder.layer.0.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.0.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.1.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.1.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.1.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.1.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.1.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.1.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.1.output.dense.weight 	 Loaded
text_branch.encoder.layer.1.output.dense.bias 	 Loaded
text_branch.encoder.layer.1.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.1.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.2.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.2.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.2.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.2.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.2.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.2.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.2.output.dense.weight 	 Loaded
text_branch.encoder.layer.2.output.dense.bias 	 Loaded
text_branch.encoder.layer.2.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.2.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.3.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.3.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.3.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.3.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.3.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.3.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.3.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.3.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.3.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.3.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.3.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.3.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.3.output.dense.weight 	 Loaded
text_branch.encoder.layer.3.output.dense.bias 	 Loaded
text_branch.encoder.layer.3.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.3.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.4.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.4.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.4.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.4.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.4.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.4.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.4.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.4.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.4.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.4.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.4.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.4.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.4.output.dense.weight 	 Loaded
text_branch.encoder.layer.4.output.dense.bias 	 Loaded
text_branch.encoder.layer.4.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.4.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.5.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.5.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.5.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.5.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.5.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.5.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.5.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.5.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.5.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.5.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.5.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.5.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.5.output.dense.weight 	 Loaded
text_branch.encoder.layer.5.output.dense.bias 	 Loaded
text_branch.encoder.layer.5.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.5.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.6.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.6.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.6.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.6.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.6.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.6.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.6.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.6.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.6.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.6.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.6.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.6.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.6.output.dense.weight 	 Loaded
text_branch.encoder.layer.6.output.dense.bias 	 Loaded
text_branch.encoder.layer.6.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.6.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.7.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.7.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.7.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.7.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.7.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.7.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.7.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.7.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.7.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.7.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.7.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.7.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.7.output.dense.weight 	 Loaded
text_branch.encoder.layer.7.output.dense.bias 	 Loaded
text_branch.encoder.layer.7.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.7.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.8.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.8.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.8.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.8.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.8.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.8.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.8.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.8.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.8.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.8.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.8.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.8.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.8.output.dense.weight 	 Loaded
text_branch.encoder.layer.8.output.dense.bias 	 Loaded
text_branch.encoder.layer.8.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.8.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.9.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.9.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.9.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.9.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.9.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.9.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.9.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.9.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.9.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.9.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.9.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.9.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.9.output.dense.weight 	 Loaded

In [ ]:
# Get text embedings from texts:
text_data = ["I love the contrastive learning", "I love the pretrain model"]
text_embed = model.get_text_embedding(text_data)
print(text_embed)
print(text_embed.shape)

[[-0.00919978  0.02500593  0.00363404 ...  0.01062    -0.00127951
  -0.0651798 ]
 [-0.02006619  0.03137505  0.08235695 ... -0.09679958  0.00108542
  -0.07113259]]
(2, 512)

In [ ]:
#!/bin/bash

!mkdir -p ./data/Clotho/caption
!mkdir -p ./data/Clotho/audio

TARGET_DIR="./data/Clotho"
CAPTION_DIR="./data/Clotho/caption"

DEV_URL="https://zenodo.org/records/4783391/files/clotho_audio_development.7z?download=1"
EVAL_URL="https://zenodo.org/records/4783391/files/clotho_audio_evaluation.7z?download=1"
VAL_URL="https://zenodo.org/records/4783391/files/clotho_audio_validation.7z?download=1"
DEV_CAP_URL="https://zenodo.org/records/4783391/files/clotho_captions_development.csv?download=1"
EVAL_CAP_URL="https://zenodo.org/records/4783391/files/clotho_captions_evaluation.csv?download=1"
VAL_CAP_URL="https://zenodo.org/records/4783391/files/clotho_captions_validation.csv?download=1"
DEV_META_URL="https://zenodo.org/records/4783391/files/clotho_metadata_development.csv?download=1"
EVAL_META_URL="https://zenodo.org/records/4783391/files/clotho_metadata_evaluation.csv?download=1"
VAL_META_URL="https://zenodo.org/records/4783391/files/clotho_metadata_validation.csv?download=1"



# Download the file
print("Downloading Clotho dataset...")
!wget -O "$TARGET_DIR/dev_metadata.csv" "$DEV_META_URL"
!wget -O "$TARGET_DIR/eval_metadata.csv" "$EVAL_META_URL"
!wget -O "$TARGET_DIR/val_metadata.csv" "$VAL_META_URL"
!wget -O "$CAPTION_DIR/eval.csv" "$EVAL_CAP_URL"
!wget -O "$CAPTION_DIR/dev.csv" "$DEV_CAP_URL"
!wget -O "$CAPTION_DIR/val.csv" "$VAL_CAP_URL"
!wget -O "$TARGET_DIR/clotho_audio_development.7z" "$DEV_URL"
!wget -O "$TARGET_DIR/clotho_audio_evaluation.7z" "$EVAL_URL"
!wget -O "$TARGET_DIR/clotho_audio_validation.7z" "$VAL_URL
!wget -O "$TARGET_DIR/clotho_audio_validation.7z" "$VAL_URL"

# Inform the user
'''
if [ $? -eq 0 ]; then
    echo "Download completed successfully."
    echo "File saved to: $OUTPUT_FILE"
else
    echo "Download failed."
fi
'''

# Install p7zip depending on OS
!brew install p7zip #macOS using homebrew
!apt-get install p7zip-full #linux/ubuntu

!7z x "$TARGET_DIR/clotho_audio_development.7z" -o./data/Clotho/audio/
!7z x "$TARGET_DIR/clotho_audio_evaluation.7z" -o./data/Clotho/audio/
!7z x "$TARGET_DIR/clotho_audio_validation.7z" -o./data/Clotho/audio/

Downloading Clotho dataset...
--2024-11-30 15:14:09--  https://zenodo.org/records/4783391/files/clotho_metadata_development.csv?download=1
Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.48.194, 188.185.43.25, ...
Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 830797 (811K) [text/plain]
Saving to: ‘./data/Clotho/dev_metadata.csv’

./data/Clotho/dev_m 100%[===================>] 811.33K  1.27MB/s    in 0.6s

2024-11-30 15:14:10 (1.27 MB/s) - ‘./data/Clotho/dev_metadata.csv’ saved [830797/830797]

--2024-11-30 15:14:10--  https://zenodo.org/records/4783391/files/clotho_metadata_evaluation.csv?download=1
Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.48.194, 188.185.43.25, ...
Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 225311 (220K) [text/plain]
Saving to: ‘./data/Clotho/eval_metadata.csv’

./data/Clotho/eval_ 100%[===================>] 220.03K   595KB/s    in 0.4s

2024-11-30 15:14:11 (595 KB/s) - ‘./data/Clotho/eval_metadata.csv’ saved [225311/225311]

--2024-11-30 15:14:11--  https://zenodo.org/records/4783391/files/clotho_metadata_validation.csv?download=1
Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.48.194, 188.185.43.25, ...
Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 224803 (220K) [text/plain]
Saving to: ‘./data/Clotho/val_metadata.csv’

./data/Clotho/val_m 100%[===================>] 219.53K   580KB/s    in 0.4s

2024-11-30 15:14:12 (580 KB/s) - ‘./data/Clotho/val_metadata.csv’ saved [224803/224803]

--2024-11-30 15:14:12--  https://zenodo.org/records/4783391/files/clotho_captions_evaluation.csv?download=1
Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.48.194, 188.185.43.25, ...
Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 361995 (354K) [text/plain]
Saving to: ‘./data/Clotho/caption/eval.csv’

./data/Clotho/capti 100%[===================>] 353.51K   697KB/s    in 0.5s

2024-11-30 15:14:13 (697 KB/s) - ‘./data/Clotho/caption/eval.csv’ saved [361995/361995]

--2024-11-30 15:14:13--  https://zenodo.org/records/4783391/files/clotho_captions_development.csv?download=1
Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.48.194, 188.185.43.25, ...
Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1336762 (1.3M) [text/plain]
Saving to: ‘./data/Clotho/caption/dev.csv’

./data/Clotho/capti 100%[===================>]   1.27M  1.70MB/s    in 0.7s

2024-11-30 15:14:14 (1.70 MB/s) - ‘./data/Clotho/caption/dev.csv’ saved [1336762/1336762]

--2024-11-30 15:14:14--  https://zenodo.org/records/4783391/files/clotho_captions_validation.csv?download=1
Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.48.194, 188.185.43.25, ...
Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 367649 (359K) [text/plain]
Saving to: ‘./data/Clotho/caption/val.csv’

./data/Clotho/capti 100%[===================>] 359.03K   710KB/s    in 0.5s

2024-11-30 15:14:15 (710 KB/s) - ‘./data/Clotho/caption/val.csv’ saved [367649/367649]

--2024-11-30 15:14:15--  https://zenodo.org/records/4783391/files/clotho_audio_development.7z?download=1
Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.48.194, 188.185.43.25, ...
Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4541582263 (4.2G) [application/octet-stream]
Saving to: ‘./data/Clotho/clotho_audio_development.7z’

./data/Clotho/cloth 100%[===================>]   4.23G  15.9MB/s    in 4m 39s

2024-11-30 15:18:55 (15.5 MB/s) - ‘./data/Clotho/clotho_audio_development.7z’ saved [4541582263/4541582263]

--2024-11-30 15:18:55--  https://zenodo.org/records/4783391/files/clotho_audio_evaluation.7z?download=1
Resolving zenodo.org (zenodo.org)... 188.185.43.25, 188.185.45.92, 188.185.48.194, ...
Connecting to zenodo.org (zenodo.org)|188.185.43.25|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1249726503 (1.2G) [application/octet-stream]
Saving to: ‘./data/Clotho/clotho_audio_evaluation.7z’

./data/Clotho/cloth 100%[===================>]   1.16G  1005KB/s    in 17m 14s

2024-11-30 15:36:09 (1.15 MB/s) - ‘./data/Clotho/clotho_audio_evaluation.7z’ saved [1249726503/1249726503]

/bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 2: syntax error: unexpected end of file
--2024-11-30 15:36:10--  https://zenodo.org/records/4783391/files/clotho_audio_validation.7z?download=1
Resolving zenodo.org (zenodo.org)... 188.185.43.25, 188.185.45.92, 188.185.48.194, ...
Connecting to zenodo.org (zenodo.org)|188.185.43.25|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1260701425 (1.2G) [application/octet-stream]
Saving to: ‘./data/Clotho/clotho_audio_validation.7z’

./data/Clotho/cloth 100%[===================>]   1.17G  1.22MB/s    in 17m 3s

2024-11-30 15:53:13 (1.18 MB/s) - ‘./data/Clotho/clotho_audio_validation.7z’ saved [1260701425/1260701425]

/bin/bash: line 1: brew: command not found
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
p7zip-full is already the newest version (16.02+dfsg-8).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Xeon(R) CPU @ 2.30GHz (306F0),ASM,AES-NI)

Scanning the drive for archives:
  0M Scan ./data/Clotho/                        1 file, 4541582263 bytes (4332 MiB)

Extracting archive: ./data/Clotho/clotho_audio_development.7z
--
Path = ./data/Clotho/clotho_audio_development.7z
Type = 7z
Physical Size = 4541582263
Headers Size = 70721
Method = Delta LZMA2:24
Solid = +
Blocks = 4


In [ ]:
import os
files = ["/content/data/Clotho/audio/development", "/content/data/Clotho/audio/evaluation"]
for folder_path in files:
  files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
  print(files)
  print(len(files))

['sail-boat-inside.wav', 'Berlin Holocaust memorial walk 111224.wav', 'church bells.wav', 'Brockenbahn.wav', 'Stoney_StormyC_Nov12.wav', 'bird-twitter.wav', 'school break noise outdoor.wav', 'cicadas at open air market cigales au marche Bonnieux.wav', 'tea_stir.wav', 'Flame thrower varying power.wav', 'Thunder in the distance, rain in proximity on 8th July 2012 in Berlin.wav', 'police_car_siren-esp.wav', 'R05_0197.wav', 'trail_footsteps_2_0725_102951.wav', 'Swiss Alp with cowbells and creek.wav', 'Slowly Walking Downhill on Dry Leaves.wav', 'wind and birds in the delta of the River Po.wav', '140704_rain.wav', 'Ambience_hum_tuning fork.wav', 'Dog food.wav', 'Interior Ambience Large Hall Baby Cries in Background.wav', 'Construction_Site_Pickhammer.wav', 'Sound_FX_House cleaning disch.wav', 'Nails crackle 3.wav', 'outdoors ambient distant village 3.wav', 'alexander_ordonez_bio_fonia_noche_rural.wav', 'Footsteps On Squeaky Wood Floor.wav', 'breathing building.wav', 'Camp Fire 1.wav', 'rain and swifts.wav', 'officeWaterPump.wav', 'starting car engine.wav', 'Pine forest soundwalk.wav', 'Modern Front Door Inside and Outside DonFX.wav', 'evening_rain.wav', 'Washing machine (clock).wav', 'Count down and drive away car rally gravel.wav', 'freesound.wav', 'Steaming milk on a consumer-grade latte maker.wav', 'bad-def01.wav', 'rainbirdsdropletmar19.wav', 'School Kids Walk.wav', 'Quarter Horse race_1-2.wav', 'dmv - waiting.wav', 'Walking Down a Road.wav', 'elvis_old_time_radio.wav', 'md10trk11.wav', '20100917.14h.thunder.rain.wav', 'World melody.wav', 'Little sreet behind a terrasse cafe.wav', 'rain_18_20_16.wav', 'Sink_Running.wav', 'water.wav', 'Rain after Thunder from Shed 2013-07-25 1.wav', 'rowing.wav', 'fabra i coats exterior 15.wav', 'Aldgate Christians.wav', 'Cardinal Key West.wav', 'Cardiff Bay fireworks.wav', '20101121.sanlucar.street.wav', ', iannaeneee iiaca, caienu niaoe iaao aaaiiaie, nooe eie n, oi e naeno aaoa ia neiinoe, caii eaaaaoia iiiineon.wav', 'Silencyo_COUNTRY_DAY_Birds_Cuckoo_Morning_6AM.wav', 'Unknown bird in rainy woods.wav', 'April dawn chorus Sydenham Hill.wav', 'NightCity hum 01 130212.wav', 'Little brook.wav', 'GreatTit.wav', 'PS3F_FOZ_Terminal_vendinha sorvete_sabado_tarde.wav', 'Lavandome los dientes, Grupo 9 Karen y Paula.wav', 'SmallJarLidScrewUnscrew.wav', 'Barking - Polyrhitmic Dog Duo.wav', 'vertrek2.wav', 'Showerhead-Underwater.wav', '09091600_BeloHorizonte_BusTerminal.wav', 'Forest  in Hungary, Debrecen, Leveles Csarda Ambient 01 (Loop).wav', '0401 Traffic_light_sound.wav', 'violin1.wav', 'Beacon2.wav', 'kijjaz - Swimming Pool Pump 01.wav', '2nd Half of a Freight Train.wav', 'Old Padlock.wav', 'GarbageTruck.wav', 'Rome Inside The Metro.wav', 'drops.wav', 'Broken printer, stalled machine.wav', 'windchim .wav', 'Birdsong2.wav', 'Wind and Traffic Ambience.wav', 'Construction_site_sounds_COMPRESSOR.wav', 'frozenBeachWalk_1.wav', 'Footdrags Dirt.wav', 'Squeaky chair.wav', 'folding paper.wav', 'Gentle rain plastic roof and metal pipes.wav', 'hereg_hungary__grain_field_2_20080712.wav', 'seagulls.wav', 'LoneCricketSeptember2013.wav', 'handspoundingdesks.wav', 'squeaky-tennis-ratchet.wav', 'October night, cicadas, crickets, jet flyover.wav', '20110719 kijjaz - Small House Contruction Site in Bangkok.wav', 'Ambience, Night Wildlife, A.wav', 'hereg_hungary__grain_field_1_20080712.wav', '080809_03_Ri_pokretneStepeniceKlompeVentilacija.wav', 'Train Station Atmosphere.wav', 'whitenoise_wah.wav', '05-Osterport_Platform_ThroughTrain.wav', 'Thunder.wav', 'Openning a water canteen.wav', 'Crack_2Eggs_and_Fry.wav', 'Shower faucet.wav', 'BI-PLANE TAXI.wav', 'City Ambience_oncoming traffic_rush hour.wav', 'fu-rin_train.wav', 'MISC_Police_Siren_Int_Onboard_003.wav', '01 car sequence.wav', 'Soundscape_GWAEtoyIS_soundstory001.wav', '6th may 2011.wav', 'rain_on_window.wav', 'StreetNoise.wav', 'resonant_sewer.wav', 'Cars_driving_slush_road.wav', 'Cloths wearing.wav', 'sonicpostcards-49GR-frenocar.wav', 'Shower, A.wav', 'Pencil Scratch 2.wav', 'sniff.wav', 'Flipping Through Notebook.wav', 'school corridor (1).wav', 'samsung_laser_printer_clog.wav', 'rain_metallic_gutter_sanus_excipio.wav', 'Tiny bells.wav', 'Motorbike driving away.wav', 'CFX-20130329-UK-DorsetRoomTone02.wav', 'Washing Dishes2.wav', 'Half bathroom with some toilet noise.wav', 'Bath Tub Running Water.wav', 'Train between wagons.wav', 'highway urban.wav', 'SidewalkCutter.wav', 'Vinil_Noise_30sec.wav', 'Fan_Ventilation_Stereo 5.wav', 'Sundsvall Harbour.wav', 'Trickling Stream.wav', 'fridaynight.wav', '120808_001.wav', 'Boulevard SummerRiver calm 01 NL 160905_0961 0962.wav', 'engine_spin_up.wav', 'Middle waves at a small pier.wav', 'FootstepsOnWoodFloor.wav', 'Elektron Analog Rytm Beat &gt; Redson EC-25 8-track tape echo.wav', 'ambient house room tone open window distant noises neighbours.wav', 'shaking and opening a water bottle.wav', 'Subping03.wav', 'Suburban Summer Nights.wav', 'Int-USMetalcoinsmoving.wav', 'violin-false-sounds.wav', 'Fire with wet wood.wav', 'Dentist Chair Hydraulics.wav', '20070814.Copenhagen.04.wav', 'atmosphere_2.wav', 'BitmapNoise2.wav', '_Stream 3 at Krka falls.wav', 'Thunder_01.wav', 'Car interior driving 1.wav', 'forest_ambience_copake_winter_1.wav', 'Class 40 arriving from Heywood.wav', 'chinesealarmclock.wav', 'just birds.wav', 'Concrete block hitting the ground.wav', 'sulivan&#39;s gultch.wav', '04638 heating bleeding valve.wav', 'Thunder - 2.wav', 'Remix of 33366__cognito_perceptu__bong_hits_with_lighter (cleaner and compressed).wav', 'Drinking &amp; swallowing soup.wav', 'coyotes going crazy before dawn.wav', 'Wood_Creak_02.wav', 'foret.au.matin.wav', 'Train Level Crossing.wav', 'Village Morning Atmos.wav', 'sw_RainWithCrickets_20100917.wav', 'Blackbird botanical gardens  Aarhus.wav', 'metal_mixing_bowl_spins_edit.wav', 'U-Bahnhof Berlin Alanderplatz U-Bahn Abfahrt.wav', 'Park Szczubeka Ulica Powsinska.wav', 'Playground assembly at Welsh Medium Primary School.wav', 'Hail and Rain in the Courtyard.wav', 'Cruiseship - outside, at the funnel next to main engine intake.wav', 'External Harddisk Starting Up.wav', 'So_little_time_so_many_frequencies.wav', 'Mobile_phone_-_Dialing_tones_slow_L_Close_R_Distant.wav', '20060706.wasp.wav', 'plastic packet lentils shake open close.wav', 'car alarm 130603.wav', 'hail on car.wav', 'Poppenweiler_Baechle mit Amsel 02_20100704.wav', 'street traffic with big trucks.wav', 'Passenger train Q1_03.wav', 'river_mouth3.wav', 'Fast Dripping water on metal with splashes.wav', 'Narrowboat - Output - Stereo Out.wav', 'R05_0581.wav', 'Carillon - GoSoundtrack.wav', 'bird in the Hague at dawn 5.wav', 'walking up steps.wav', 'SprayPaint&amp;Gravel.wav', 'CFX-20130331-UK-DorsetSeaCliff04.wav', 'footsteps on wood.wav', '130915 - Interior-Hard Rain with 2 Skylights.wav', 'Construction_Site_Cat_2.wav', 'Class 66 At Aliwal Lane Crossing Whittlesea.wav', 'bathtub drain.wav', 'People Trompenburg 090928.wav', 'Eyelit cabinet.wav', 'Wind moaning through gap in door2.wav', 'Construction 1.wav', 'Spitfire Commentry Introduction and Fly Past - 2005-08-07@16_54_1.wav', 'Plastic Hit 1.wav', 'wind_howl2_stereo.wav', 'flush1.wav', 'wolombi-road.wav', 'TropicalBirds1.wav', 'snow.wav', 'SongSparrowSongMarch52012.wav', 'eating_cabbage.wav', 'Applause - Crowd - 4.wav', 'Sawing 2x4.wav', 'md1trk19.wav', '120127_0000 train-interior-conversations.wav', '120127_train-departure.wav', 'amazon 04.wav', 'Metallic Strums.wav', 'Tbilisi Sea.wav', 'in the cafe.wav', 'Light Footsteps.wav', 'boiling-kettle-noise.wav', 'winter wren wind leaves.wav', '20090619 kijjaz - Contruction Site Radio 02.wav', 'Birds in the city 1.wav', 'Sink faucet.wav', '20100423.river.02.wav', 'chaffinch_black_forest.wav', 'balloon.wav', 'Martian Seas.wav', 'Omsk_Victory_park_7.wav', 'Sounds of the R-building.wav', 'FiaGT.08.PotreroFunes.RedHotBrakes.5.1.wav', 'Modern Front Door  from outside DonFX.wav', 'Fenway Park Sep 19 2010.wav', 'Cityscape 03 100208.wav', 'noisy-sink-tap.wav', 'RnSqScmlPadC3.wav', 'Plaza_de_la_Revolucion_perro.wav', 'murmur_on_ferry_1.wav', 'HP Envy Printer Startup.wav', 'CameraHandling.wav', 'Galle Road.wav', 'rotating sprinkler.wav', 'Waterfalls_00217.wav', 'mowinglawn_giethoorn_fspedit.wav', 'Paris pluie sirenes.wav', 'Te Atatu Library.wav', 'swamp.wav', 'ringring.wav', 'Chalk Writing - Fast.wav', 'BoyRacer.wav', 'Chain pick up from &amp; drop on small piece of metal.wav', 'waves.wav', '20070504.Sierra.stream.04.wav', 'AMB Ghana Rain, Vox, Goats 1 LB.wav', '20081130_walking_in_snow_with_snowshoes.wav', 'creek.wav', 'Breathing Man Machine 2.wav', 'static_weather_report.wav', 'gargnano.wav', 'INT Bathroom tone 1.wav', 'footsteps woodland.wav', 'Rain - 1.wav', 'PauseConference_youngerPeople.wav', 'walking in snow 2.wav', 'Popping popcorn.wav', 'DC Metro - Interior 1.wav', 'metal clink.wav', 'Old alarm clock ticking.wav', 'City_Ambience_Cars_Night.wav', 'Cityscape 04 090617.wav', 'PassingDieselCar.wav', 'dishwasher beep and motor.wav', 'metal soft scrape.wav', '20101112.chivos.wav', 'windy winter day, wind in trees, leaves, metallic object rattling.wav', 'INT Factory nearby 3 water dripping.wav', 'md1trk31.wav', 'La Barca i La Tempesta.wav', 'Geese Fly Over.wav', 'Kicking Pile of Bottles and Cans.wav', 'draining board metal drip on metal.wav', 'FP_Rainstorm.wav', 'plastic-straw-whistles.wav', 'Copper cylinder sound.wav', 'church-eglise #1.wav', 'crumpleTissuePaper.wav', 'near a little mountain stream.wav', 'Whistling antarctic blizzard.wav', 'Rain on street Leuvehaven 100609.wav', 'street steps child car.wav', 'Lake At Night.wav', 'Ambience in spaceship.wav', 'mass in croatian cathedral.wav', 'Chalk on Pavement.wav', 'Machine Ambiance 2.wav', 'breathingsfx.wav', 'barn_2.wav', 'Wind and Sprinkling Rain.wav', 'Wind Through a Pipe.wav', '160170_Wind Blowing door_OWI.wav', 'glass-sweeping.wav', 'hg.wav', 'wind_howling_01.wav', 'coast wave kids far 160710_0914.wav', 'kraaien.wav', 'Fog in the trees with wind.wav', 'nnus_train_horn_track_noise.wav', 'BeforeTheRain(Wind).wav', 'Geese1 - (Apollonia&#39;s sPA) 18_44 05.10.wav', 'Leather Jacket Wooshes.wav', 'birds and plane.wav', '19_VACCL.wav', 'fh_Paper_Swipe_01_01.wav', 'Washing Machine Water Filling Up.wav', 'winding spring.wav', 'fridge_back.wav', 'train boat.wav', 'Liverpool St Station main hall.wav', 'Air condition running.wav', 'Tapping on large window 120bpm.wav', 'Barking Aldi Dog.wav', 'Metal Till Cash Drawer Slide In And Out.wav', 'barrelhits.wav', 'R05_0484.wav', 'Kids chatter Primary School Birmingham UK.wav', 'Ocean Waves of Norfolk.wav', 'Hilden, night, open field crickets, light traffic.wav', 'Locomotive Horn (whistle).wav', 'Grannie&#39;s old coffee bean mill.wav', 'snow on leaves.wav', 'Wading in Shallow Water.wav', 'gardensoundscape.wav', 'water in bottle.wav', 'Silencyo_CC_Field_Cicadas_French Children Playing_Wind_Dog_Distant Traffic.wav', 'dryer_turn_on_open_door_close_door_24_96_mono.wav', 'Truck passed high speed in the rain.wav', 'delphis AMBIENT CAR edit.wav', 'Extractor Fan 03.wav', 'SoulStation.wav', 'RailStation_CargoTrainGoFromStandBy--.wav', 'car acceleration sequence.wav', 'Snapping twig.wav', 'MAINLAND.wav', 'Freight train (VL10)  (Zoom H6 recorder).wav', 'Int- Mom&amp;Dadcondooropenandclose.wav', 'EXT STREAM DAY (WITH GEESE) 96K.wav', '100302_07.wav', 'Rain Thunder &amp; Water (Stereo).wav', 'Deep Space (Cinematic Soundscape).wav', 'London Indoor Playground.wav', 'Walking In Snow.wav', 'entrance to the mosque on Rhodes, prayers, scooter in the background.wav', 'weekly market [2].wav', 'Boleskine, forest brook.wav', 'whisperingsecret.wav', 'dare16_orchestral_scape2.wav', 'Misc_bird_calls_light_traffic.wav', 'Morning In Palyem (North Goa, India).wav', 'walking in snow in the woods.wav', 'outside general noise.wav', 'Printer Setting Up.wav', 'Hayling Ferry.wav', 'urban-bees.wav', '080909_03_machine_motor.wav', 'Kettle 01.wav', 'copenhagen atmosphere around fountain 2012-07-10.wav', 'Home, Sweet Broken Neve.wav', 'Ambience_hurricane tube.wav', 'restaurant2.wav', 'Drilling holes 090416.wav', 'Imaginary_Car_Traffic.wav', 'Dripping water.wav', 'River 2.wav', 'pases_0.wav', 'hanoiairport01.wav', 'Rumpling_Paper_01.wav', 'merlin engine.wav', 'Nails gliding on skin.wav', '002_78_rpm_vinyl_noise_44_16_lossless.wav', 'Hammer and nail.wav', 'meadow brook bees.wav', 'angry parisian drivers.wav', 'Autumnal Ambient 24 Bits 48 Khz.wav', 'rumble metal.wav', 'Supermarket.wav', 'Digging with shovel.wav', 'Shipwreck underwater 01.wav', 'spaceship engine2.wav', 'Holyfield vs.wav', '0112_032412 bubbling brook 1min 96k.wav', 'break_through_blocked_door.wav', 'quarters from machine.wav', 'stretched bell.wav', 'tree frogs.wav', 'Summer night storm.wav', 'Surf on small pebbles, Caloura (02.11.wav', 'Bird Song.wav', 'Walking through dry leaves, close-by and afar.wav', 'Busy bar ambient sound.wav', 'B13h35m19s11jan2008.wav', 'RedWingBlackBirdShoppingCenter.wav', 'car burning.wav', 'Shower 1.wav', 'Gym&#39;sHall.wav', 'chinatown_park.wav', 'recycling paper.wav', 'JSB_Small Splashes.wav', 'stanley_and_reese_bath_01.wav', 'bath in a river.wav', '111229-000_hail_storm_on_window_pane.wav', 'kettle.whistle.wav', 'Cigarette_roll_pack.wav', '20091211.barking.stairs.wav', 'Pig7 - Nothing Out There.wav', 'Construction Zone.wav', 'CABINET DRAWER.wav', 'Brook with village atmosphere.wav', 'Distant Hammer.wav', 'Walk From Nanjing Road East To Peoples Square.wav', 'nongateRave.wav', 'screen-door-slam.wav', 'Freight Train Crossing.wav', 'Geroezemoes.wav', 'Dusting.wav', 'autospasandociudadnoche1.wav', 'FranklinStoveDoorGroansandHits_RX.wav', 'pots and pans.wav', 'crescendo meE01vtH.wav', 'crumpling paper.wav', 'Kyle of Lochalsh harbour.wav', 'dryer_long_1.wav', 'Bic pen handling noises.wav', '2 Gardener - May 2013 - Take01 - ZOOM H2n.wav', 'two large cobblestone blocks.wav', 'mountain river 06-09-2012.wav', 'torch.wav', 'train-1.wav', 'Plane crash - black box.wav', 'FreeSound Loop 1.wav', 'dull metal.wav', 'souffle_me_tallique.wav', 'Laughing Kookaburra.wav', '20100213.bus.ride.wav', 'fan_2_300513.wav', 'Christmas lights, bulbs clinking, light handling.wav', '20090826.path.wav', 'safe.wav', 'Waves_00512.wav', 'gurgles02.wav', 'Julian&#39;s Door - open and close, hinge only.wav', 'SoundscapeTehRi.wav', 'miau.wav', 'weed whacker june 2002 24 bit.wav', '20101012.pasacalle.wav', '080920_02_song_under_metal.wav', 'udelnaya_zug.wav', 'Forbidden Purr01.wav', 'Stockholm subway C20 train departing.wav', 'Steam Train In Motion 4 (from inside window rattling).wav', 'file0680 crowd.wav', 'Empty Field Ambience.wav', 'Herd Of Cows Mooing.wav', 'Coffee Machine Trickling.wav', 'Coffee Maker Brewing.wav', 'Birds, Krka National Park, Croatia edit.wav', 'Big scary Footsteps.wav', 'mijo + folk och skotrar 1.wav', 'Dutch air-raid warning 02.wav', 'rambla_mar_pont.wav', 'Fast flowing water 1.wav', '20080918.boots.door.wav', 'Corn Husking Sequence x2.wav', 'vacuum power head.wav', 'Mysound-IDES-FRlittle-bell.wav', '160917-eichelherr000.wav', '18 hn_trafficlightcontroller.wav', 'School.wav', 'car driving around.wav', 'Woodchipper Start (heavy machine) 02.wav', 'RAIN ON CONCRETE.wav', 'DR-100_0068.wav', 'Llaves.wav', 'City And Bugs.wav', 'Large ship engine running recorded in cabin.wav', 'FP_Diesel_Tractor_Driving.wav', 'metal door creaking loud (borQue).wav', 'Fumigadora.wav', 'Chickadees Singing.wav', 'Bad com link sound.wav', '20100306.visitors.wav', 'hammer.wav', 'Gas Oven.wav', 'Kocking door and open door.wav', '20080629.campeones.01.wav', 'evening street.wav', 'Steps_on_Gravel.wav', 'bird-chatter.wav', 'Auto_with_fadeout.wav', 'AmbianceBackyard_Quiet_bip.wav', 'BC inside a dog.wav', 'footsteps fast then VERY slow (rob).wav', 'background(bar or pub).wav', 'Brooklyn Residential Street.wav', 'Sizzling Bacon.wav', 'T12_Huber_Walking on Gravel.wav', 'Tube deflating.wav', 'Cleaning Dishes in Kitchen Sink.wav', 'Coins falling on wood.wav', 'Gasoil train leaves station, slowly. Tupiza, Bolivia.wav', 'Boiling Geothermal Mud.wav', 'CR FunnyMachine.wav', 'earth_movement.wav', 'R05_0242.wav', 'Ambience Shopping mall.wav', 'Lillibullero Whistled.wav', 'Car Keys.wav', 'Strong Wind.wav', 'molding_machine.wav', 'kitchen metal.wav', '0224 Plaza_Mayor_escaleras.wav', 'night_train_inside.wav', 'Cat Eating.wav', '120708 granul 01.wav', 'jet_engine.wav', 'greece_boat_piraeus.wav', 'Crowd Shouting.wav', 'Soda in vinegar.wav', 'top_of_hill_estialescq_minimal_soundscape.wav', 'birds-Udaipur-Saheliyon-Ki-Bari.wav', 'je_footstepsCement.wav', 'Uppsala Streetbusker accordion 1.wav', 'toy rattle 1.wav', 'Flock of sheep being moved.wav', 'A wet and cold winter afternoon at Cholsey.wav', 'Skate pass on road 4.wav', 'wind-quiberon01.wav', 'school corridor (2).wav', 'Light rain.wav', 'Washing_machine_20130512.wav', 'metro underground ambient noisy transport catalan barcelona minimal tickling glitch.wav', 'Hallway with Water Fountain Noise.wav', 'wind_long_grass_24_96_mono.wav', '150209 Trevor Webb Air Cyclinder.wav', '20100418.marshes.storm.01.wav', 'keurigcoffee.wav', 'London Underground_Boarding and Interior.wav', 'light rain ambience.wav', '20070218.footsteps.wav', 'Pipe hit.wav', 'Household - Rain on Conservatory Roof.wav', 'IKEA_Cafeteria.wav', 'SYnth_NoisesAX9.wav', 'Chalk on chalk board.wav', '05687 morning birds ambience.wav', 'Air door sound 2.wav', '2009-07-17_1047_Mercado Bolhao between butcher&#39;s and beans.wav', 'Motorbike.wav', 'Freight Train Slow2 - Mixdown.wav', 'folding_pages.wav', 'cd_load_26sedit.wav', 'golpeando cosas metalicas.wav', 'Lunch Box Open and Close.wav', 'Breathing.wav', 'French playing football.wav', 'Knife_Swords.wav', 'Jilkakilka_Garden rain.wav', 'SUBWAY_02.wav', '20100802.sawing.wav', '160718 HSN skateboarders 1.wav', '1400 am static.wav', 'riverside evening 01 SHORT.wav', '&quot;BCat Bites a Bit&quot; .wav', 'Tropical beach_waves on pebbled shore.wav', 'AC Unit.wav', 'Thunder&amp;Rain1.wav', 'Fly fishing - winding in reel fast, slow.wav', 'Carillon Zuiderkerk Amsterdam.wav', 'Street_Genova.wav', 'FallWindThroughFieldWeedsInsectsOct3rd2014.wav', 'Maria Hernandez Park September 1st.wav', 'snore snoring night ambient crickets bugs white noise.wav', 'Floor_trading5.wav', 'Handling Bottle.wav', 'STE-027FIRE.wav', 'Applause_encore.wav', 'Open Window + Train Passes.wav', 'stonemachine.wav', 'Big Sur Pfeiffer Beach Park Stream.wav', 'crossing tracks.wav', 'SnappingBamboo.wav', 'Fiaker.wav', '20100423.river.01.wav', 'Rain on a caravan roof.wav', 'Cold Front Blowing In.wav', 'bubbling02.wav', 'two trains-casablanca.wav', 'auto int heat blast max.wav', '20061205.washing.machine.filling.wav', 'degge.wav', 'FootstepsonWoodFloor-EDITED.wav', 'APPROACHING_STORM_2_0809_183204.wav', 'Sewanee Carillon.wav', 'rain_and_thunder.wav', '0327 Quiet_road_Naebang.wav', 'Shopping Mall, ambience.wav', 'Starting car recorded from inside.wav', 'Glass on concrete.wav', 'Calm Morning Outdoor Ambience.wav', 'Submarine Diesel Engine 002.wav', 'motor city atmosphere.wav', 'Buddhist Bells.wav', 'defective machine L38_m.wav', 'Industrial Machine Cycle.wav', 'RailStation_CargoTrainGo--.wav', 'Foley, cracking floors, take-4.wav', 'FP_Refrigerator_Door_Squeak.wav', 'Chalk_Board_Writing_Classroom_Natasha_Martinez_031215.wav', 'fr9 07 street sounds.wav', 'teethbrush_1-2.wav', 'clock-chiming-01.wav', 'Neighbourhood evening ambience.wav', 'traffic_control.wav', 'Squeak Finger on Glass.wav', 'plastic_ruler.wav', 'Running Water Into Metal Sink Basin.wav', 'LONG APPLAUSE.wav', 'the sound of working injection molding machine - rear.wav', 'Setting Drink Down.wav', 'Paging through a book.wav', 'extractor_hood.wav', 'WATER DRIP ECHO LOW PITCH COMPRESSED.wav', 'Kitchen Clock Ticking.wav', 'Cathedral Sqaure buskers.wav', 'rainyday.wav', '20091224.bells.02.wav', 'Box of sweets.wav', 'VNP_crater_rim_01.wav', '24may2010loudestthunder.wav', 'skateboardonstreet_1-2.wav', 'Noisy Max 5.wav', 'Highway Ambience.wav', 'Walking alongside the road.wav', 'waterfall.wav', 'chicken.wav'

In [ ]:
import pandas as pd
import os
csv_dataset = pd.read_csv("/content/clotho_development_gpt4.csv")
csv_dataset.head()


raw_files_clotho = os.listdir("/content/data/Clotho/audio/development")
csv_dataset['Audio file'].isin(raw_files_clotho).value_counts()

Audio file
True     3837
False       2
Name: count, dtype: int64

In [ ]:
def process_entailment_data(csv_path):
  df = pd.read_csv(csv_path)
  df_entailment = pd.DataFrame()
  labels = ["Entailment", "Neutral", "Contradiction"]
  for i, label in enumerate(labels):
    if df_entailment is None:
      temp = df[["Audio file", "Caption", label]]
      temp.rename(columns={label: 'Hypothese'}, inplace=True)
      temp["label"] = i
      df_entailment = temp["label"]
    else:
      temp = df[["Audio file", "Caption", label]]
      temp.rename(columns={label: 'Hypothese'}, inplace=True)
      temp["label"] = i
      df_entailment = pd.concat([df_entailment, temp], ignore_index = True)
  return df_entailment

In [ ]:
x = process_entailment_data("/content/clotho_evaluation_gpt4.csv")
x

<ipython-input-7-17da450066ad>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp.rename(columns={label: 'Hypothese'}, inplace=True)
<ipython-input-7-17da450066ad>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["label"] = i
<ipython-input-7-17da450066ad>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp.rename(columns={label: 'Hypothese'}, inplace=True)
<ipython-input-7-17da450066ad>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["label"] = i
<ipython-input-7-17da450066ad>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp.rename(columns={label: 'Hypothese'}, inplace=True)
<ipython-input-7-17da450066ad>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["label"] = i

,Audio file,Caption,Hypothese,label
0,Santa Motor.wav,['A machine whines and squeals while rhythmica...,There is a repetitive mechanical operation inv...,0
1,Radio Garble.wav,['A radio dispatcher and an officer are commun...,There is a conversation over a walkie-talkie w...,0
2,Radio Fuzz for Old Radio Broadcast FF233.wav,['A radio tuner has been positioned in between...,A radio emits static noise due to being tuned ...,0
3,toy rattle 2.wav,['A person winding up a device and then jingli...,There is a sound of a mechanism being operated...,0
4,Blade Big.wav,['A person is pulling silverware out of the di...,There are metallic sounds associated with hand...,0
...,...,...,...,...
3130,080809_05_FontanaKoblerov.wav,"['A drain with heavy rain pouring into it.', '...",A quiet snowfall blankets the ground.,2
3131,ResidentialFallNight_crickets.wav,['Cars are driving past and crickets are chirp...,A quiet room with no movement or outside noise.,2
3132,growling thunder.wav,['Heavy vehicle moving on the road with loud n...,The environment is quiet and serene without an...,2
3133,Traffic and pedestrians.wav,['A person walking back and forth in the rain ...,Indoor environment with complete silence.,2
3134,FR.BirdChatAmbience.26.wav,['Children are talking to each other and birds...,A quiet library with no conversation or birdsong.,2

In [ ]:
# Define the batch size
batch_size = 200  # Adjust this size as needed based on memory constraints

# Convert the 'Hypothese' column to a list of strings
hypothese_text = x["Hypothese"].astype(str).tolist()

# Initialize an empty list to store embeddings
all_embeddings = []

# Process the text in batches
for i in range(0, len(hypothese_text), batch_size):
    print(i)
    if i+batch_size > len(hypothese_text):
      batch = hypothese_text[i:]
    else:
      batch = hypothese_text[i:i + batch_size]
    batch_embeddings = model.get_text_embedding(batch)
    all_embeddings.append(batch_embeddings)

# Concatenate all embeddings
for i in range(len(all_embeddings)):
  all_embeddings[i] = torch.tensor(all_embeddings[i])
text_embeddings = torch.cat(all_embeddings, dim=0)
print(text_embeddings.shape)

# Save the final embeddings
torch.save(text_embeddings, '/content/data/eval_text_embeddings')

0
200
400
600
800
1000
1200
1400
1600
1800
2000
2200
2400
2600
2800
3000
torch.Size([3135, 512])

In [ ]:
import torch
import laion_clap
import numpy as np
from pathlib import Path
from tqdm import tqdm

def get_clap_embeddings_batch(
    audio_paths,
    batch_size=32,
    device='cuda' if torch.cuda.is_available() else 'cpu'
):
    """
    Generate CLAP embeddings for multiple audio files in batches
    """
    model = laion_clap.CLAP_Module(enable_fusion=False, device=device)

    all_embeddings = []

    # Process in batches
    for i in tqdm(range(0, len(audio_paths), batch_size)):
        batch_paths = audio_paths[i:i + batch_size]
        embeddings = model.get_audio_embedding_from_filelist(batch_paths)
        all_embeddings.append(embeddings)

    return all_embeddings

if __name__ == "__main__":
    audio_dir = "/content/data/Clotho/audio/development"
    audio_paths = list(Path(audio_dir).glob("*.wav"))

    # Get embeddings
    audio_embeddings = get_clap_embeddings_batch(audio_paths)
    for i in range(len(audio_embeddings)):
      audio_embeddings[i] = torch.tensor(audio_embeddings[i])
    audio_embeddings = torch.cat(audio_embeddings, dim=0)

    # Save embeddings
    torch.save(audio_embeddings, '/content/data/dev_audio_embeddings')
    print(f"Saved embeddings with shape: {audio_embeddings.shape}")

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
100%|██████████| 120/120 [02:35<00:00,  1.30s/it]

Saved embeddings with shape: torch.Size([3839, 512])

Classifier

In [ ]:
!pip install torchsummaryX==1.1.0 wandb --quiet

In [ ]:
import torch
import numpy as np
from torchsummaryX import summary
import sklearn
import gc
import zipfile
import pandas as pd
from tqdm.auto import tqdm
import os
import datetime
import wandb
from torch.optim import lr_scheduler
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Device: ", device)

Device:  cuda

In [ ]:
dev_audio = torch.load("/content/data/dev_audio_embeddings", weights_only=True)
dev_audio = dev_audio.repeat(3,1)
dev_text = torch.load("/content/data/dev_text_embeddings", weights_only=True)
dev_label = torch.load("/content/drive/MyDrive/Dataset/11785 Project/dev_label", weights_only=True)

val_audio = torch.load("/content/drive/MyDrive/Dataset/11785 Project/val_audio_embeddings", weights_only=True)
val_audio = val_audio.repeat(3,1)
val_text = torch.load("/content/drive/MyDrive/Dataset/11785 Project/val_text_embeddings", weights_only=True)
val_label = torch.load("/content/drive/MyDrive/Dataset/11785 Project/val_label", weights_only=True)

eval_audio = torch.load("/content/drive/MyDrive/Dataset/11785 Project/eval_audio_embeddings", weights_only=True)
eval_audio = eval_audio.repeat(3,1)
eval_text = torch.load("/content/drive/MyDrive/Dataset/11785 Project/eval_text_embeddings", weights_only=True)
eval_label = torch.load("/content/drive/MyDrive/Dataset/11785 Project/eval_label", weights_only=True)

**RESTART**

In [ ]:
!pip install msclap
from msclap import CLAP

# Load model (Choose between versions '2022' or '2023')
# The model weight will be downloaded automatically if `model_fp` is not specified
clap_model = CLAP(version = '2022', use_cuda=False)

Collecting msclap
  Downloading msclap-1.3.3-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: librosa<0.11.0,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from msclap) (0.10.2.post1)
Collecting numba<0.59.0,>=0.58.0 (from msclap)
  Downloading numba-0.58.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: numpy<2.0.0,>=1.23.0 in /usr/local/lib/python3.10/dist-packages (from msclap) (1.23.5)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from msclap) (2.1.4)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in /usr/local/lib/python3.10/dist-packages (from msclap) (6.0.2)
Requirement already satisfied: scikit-learn<2.0.0,>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from msclap) (1.5.2)
Requirement already satisfied: torch<3.0.0,>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from msclap) (2.4.1+cu121)
Requirement already satisfied: torchaudio<3.0.0,>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from msclap) (2.4.1+cu121)
Requirement already satisfied: torchlibrosa<0.2.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from msclap) (0.1.0)
Collecting torchvision<0.17.0,>=0.16.0 (from msclap)
  Downloading torchvision-0.16.2-cp310-cp310-manylinux1_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in /usr/local/lib/python3.10/dist-packages (from msclap) (4.66.5)
Requirement already satisfied: transformers<5.0.0,>=4.34.0 in /usr/local/lib/python3.10/dist-packages (from msclap) (4.44.2)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (3.0.1)
Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (1.13.1)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (4.4.2)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (0.12.1)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (0.5.0.post1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (4.12.2)
Requirement already satisfied: lazy-loader>=0.1 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.10/dist-packages (from librosa<0.11.0,>=0.10.1->msclap) (1.0.8)
Collecting llvmlite<0.42,>=0.41.0dev0 (from numba<0.59.0,>=0.58.0->msclap)
  Downloading llvmlite-0.41.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.0->msclap) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.0->msclap) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.0->msclap) (2024.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2.0.0,>=1.3.1->msclap) (3.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch<3.0.0,>=2.1.0->msclap) (3.16.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch<3.0.0,>=2.1.0->msclap) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch<3.0.0,>=2.1.0->msclap) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch<3.0.0,>=2.1.0->msclap) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch<3.0.0,>=2.1.0->msclap) (2024.6.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from torchvision<0.17.0,>=0.16.0->msclap) (2.32.3)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision<0.17.0,>=0.16.0 (from msclap)
  Downloading torchvision-0.16.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.6 kB)
  Downloading torchvision-0.16.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.6 kB)
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.5.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.5.1-cp310-cp310-manylinux1_x86_64.whl.metadata (28 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.1.0 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading triton-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting sympy==1.13.1 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch<3.0.0,>=2.1.0->msclap) (1.3.0)
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.5.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.5.0-cp310-cp310-manylinux1_x86_64.whl.metadata (28 kB)
INFO: pip is still looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.4.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
  Downloading torchaudio-2.4.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.4.0-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.0.0 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading triton-3.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.5 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.3.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.3.1-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting triton==2.3.1 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading triton-2.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.3.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.3.0-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting triton==2.3.0 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading triton-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.2.2-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting nvidia-nccl-cu12==2.19.3 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting triton==2.2.0 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading triton-2.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.2.1-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.2.1-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.2.0-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.2.0-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
Collecting torchaudio<3.0.0,>=2.1.0 (from msclap)
  Downloading torchaudio-2.1.2-cp310-cp310-manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting torch<3.0.0,>=2.1.0 (from msclap)
  Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
Collecting nvidia-nccl-cu12==2.18.1 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl.metadata (1.8 kB)
Collecting triton==2.1.0 (from torch<3.0.0,>=2.1.0->msclap)
  Downloading triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision<0.17.0,>=0.16.0->msclap) (10.4.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->msclap) (0.24.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->msclap) (24.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->msclap) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->msclap) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.34.0->msclap) (0.19.1)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.10/dist-packages (from pooch>=1.1->librosa<0.11.0,>=0.10.1->msclap) (4.3.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.0->msclap) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision<0.17.0,>=0.16.0->msclap) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision<0.17.0,>=0.16.0->msclap) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision<0.17.0,>=0.16.0->msclap) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->torchvision<0.17.0,>=0.16.0->msclap) (2024.8.30)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.10/dist-packages (from soundfile>=0.12.1->librosa<0.11.0,>=0.10.1->msclap) (1.17.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch<3.0.0,>=2.1.0->msclap) (2.1.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0->soundfile>=0.12.1->librosa<0.11.0,>=0.10.1->msclap) (2.22)
Downloading msclap-1.3.3-py3-none-any.whl (31 kB)
Downloading numba-0.58.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 43.5 MB/s eta 0:00:00
Downloading torchaudio-2.1.2-cp310-cp310-manylinux1_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 88.2 MB/s eta 0:00:00
Downloading torch-2.1.2-cp310-cp310-manylinux1_x86_64.whl (670.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 2.3 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.6 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 83.7 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 69.7 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 65.6 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.2 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 15.8 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 34.5 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 15.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl (209.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 6.8 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 14.0 MB/s eta 0:00:00
Downloading triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 MB 21.6 MB/s eta 0:00:00
Downloading torchvision-0.16.2-cp310-cp310-manylinux1_x86_64.whl (6.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 100.9 MB/s eta 0:00:00
Downloading llvmlite-0.41.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 MB 44.2 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 77.0 MB/s eta 0:00:00
Installing collected packages: triton, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, llvmlite, nvidia-cusparse-cu12, nvidia-cudnn-cu12, numba, nvidia-cusolver-cu12, torch, torchvision, torchaudio, msclap
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.23.4
    Uninstalling nvidia-nccl-cu12-2.23.4:
      Successfully uninstalled nvidia-nccl-cu12-2.23.4
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.43.0
    Uninstalling llvmlite-0.43.0:
      Successfully uninstalled llvmlite-0.43.0
  Attempting uninstall: numba
    Found existing installation: numba 0.60.0
    Uninstalling numba-0.60.0:
      Successfully uninstalled numba-0.60.0
  Attempting uninstall: torch
    Found existing installation: torch 2.4.1+cu121
    Uninstalling torch-2.4.1+cu121:
      Successfully uninstalled torch-2.4.1+cu121
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.19.1+cu121
    Uninstalling torchvision-0.19.1+cu121:
      Successfully uninstalled torchvision-0.19.1+cu121
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.4.1+cu121
    Uninstalling torchaudio-2.4.1+cu121:
      Successfully uninstalled torchaudio-2.4.1+cu121

CLAP_weights_2022.pth:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
!pip install laion-clap
laion_model = laion_clap.CLAP_Module(enable_fusion=False)
laion_model.load_ckpt() # download the default pretrained checkpoint.

Requirement already satisfied: laion-clap in /usr/local/lib/python3.10/dist-packages (1.1.6)
Requirement already satisfied: numpy==1.23.5 in /usr/local/lib/python3.10/dist-packages (from laion-clap) (1.23.5)
Requirement already satisfied: soundfile in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.12.1)
Requirement already satisfied: librosa in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.10.2.post1)
Requirement already satisfied: torchlibrosa in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.1.0)
Requirement already satisfied: ftfy in /usr/local/lib/python3.10/dist-packages (from laion-clap) (6.3.1)
Requirement already satisfied: braceexpand in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.1.7)
Requirement already satisfied: webdataset in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.2.100)
Requirement already satisfied: wget in /usr/local/lib/python3.10/dist-packages (from laion-clap) (3.2)
Requirement already satisfied: wandb in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.18.7)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.10/dist-packages (from laion-clap) (0.41.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from laion-clap) (1.13.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from laion-clap) (1.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from laion-clap) (2.1.4)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from laion-clap) (3.11.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from laion-clap) (4.66.5)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from laion-clap) (2024.9.11)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (from laion-clap) (4.44.2)
Requirement already satisfied: progressbar in /usr/local/lib/python3.10/dist-packages (from laion-clap) (2.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from ftfy->laion-clap) (0.2.13)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (3.0.1)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (4.4.2)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (0.58.1)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (0.5.0.post1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (4.12.2)
Requirement already satisfied: lazy-loader>=0.1 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.10/dist-packages (from librosa->laion-clap) (1.0.8)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->laion-clap) (3.5.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.10/dist-packages (from soundfile->laion-clap) (1.17.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->laion-clap) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->laion-clap) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->laion-clap) (2024.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (0.24.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers->laion-clap) (0.19.1)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (3.1.43)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (4.3.6)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (3.20.3)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (5.9.5)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (2.19.0)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (1.3.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb->laion-clap) (71.0.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0->soundfile->laion-clap) (2.22)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from docker-pycreds>=0.4.0->wandb->laion-clap) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb->laion-clap) (4.0.11)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers->laion-clap) (2024.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->laion-clap) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->laion-clap) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->laion-clap) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers->laion-clap) (2024.8.30)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb->laion-clap) (5.0.1)
Load our best checkpoint in the paper.
The checkpoint is already downloaded
Load Checkpoint...
logit_scale_a 	 Loaded
logit_scale_t 	 Loaded
audio_branch.spectrogram_extractor.stft.conv_real.weight 	 Loaded
audio_branch.spectrogram_extractor.stft.conv_imag.weight 	 Loaded
audio_branch.logmel_extractor.melW 	 Loaded
audio_branch.bn0.weight 	 Loaded
audio_branch.bn0.bias 	 Loaded
audio_branch.patch_embed.proj.weight 	 Loaded
audio_branch.patch_embed.proj.bias 	 Loaded
audio_branch.patch_embed.norm.weight 	 Loaded
audio_branch.patch_embed.norm.bias 	 Loaded
audio_branch.layers.0.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.0.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.0.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.0.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.0.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.0.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.0.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.0.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.0.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.0.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.0.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.0.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.0.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.0.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.0.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.0.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.0.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.0.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.0.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.0.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.0.downsample.reduction.weight 	 Loaded
audio_branch.layers.0.downsample.norm.weight 	 Loaded
audio_branch.layers.0.downsample.norm.bias 	 Loaded
audio_branch.layers.1.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.1.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.1.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.1.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.1.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.1.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.1.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.1.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.1.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.1.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.1.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.1.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.1.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.1.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.1.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.1.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.1.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.1.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.1.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.1.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.1.downsample.reduction.weight 	 Loaded
audio_branch.layers.1.downsample.norm.weight 	 Loaded
audio_branch.layers.1.downsample.norm.bias 	 Loaded
audio_branch.layers.2.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.2.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.2.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.2.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.2.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.2.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.2.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.2.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.2.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.2.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.2.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.3.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.3.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.3.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.3.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.3.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.3.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.3.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.3.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.3.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.3.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.4.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.4.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.4.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.4.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.4.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.4.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.4.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.4.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.4.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.4.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.blocks.5.norm1.weight 	 Loaded
audio_branch.layers.2.blocks.5.norm1.bias 	 Loaded
audio_branch.layers.2.blocks.5.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.2.blocks.5.attn.qkv.weight 	 Loaded
audio_branch.layers.2.blocks.5.attn.qkv.bias 	 Loaded
audio_branch.layers.2.blocks.5.attn.proj.weight 	 Loaded
audio_branch.layers.2.blocks.5.attn.proj.bias 	 Loaded
audio_branch.layers.2.blocks.5.norm2.weight 	 Loaded
audio_branch.layers.2.blocks.5.norm2.bias 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc1.weight 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc1.bias 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc2.weight 	 Loaded
audio_branch.layers.2.blocks.5.mlp.fc2.bias 	 Loaded
audio_branch.layers.2.downsample.reduction.weight 	 Loaded
audio_branch.layers.2.downsample.norm.weight 	 Loaded
audio_branch.layers.2.downsample.norm.bias 	 Loaded
audio_branch.layers.3.blocks.0.norm1.weight 	 Loaded
audio_branch.layers.3.blocks.0.norm1.bias 	 Loaded
audio_branch.layers.3.blocks.0.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.3.blocks.0.attn.qkv.weight 	 Loaded
audio_branch.layers.3.blocks.0.attn.qkv.bias 	 Loaded
audio_branch.layers.3.blocks.0.attn.proj.weight 	 Loaded
audio_branch.layers.3.blocks.0.attn.proj.bias 	 Loaded
audio_branch.layers.3.blocks.0.norm2.weight 	 Loaded
audio_branch.layers.3.blocks.0.norm2.bias 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc1.weight 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc1.bias 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc2.weight 	 Loaded
audio_branch.layers.3.blocks.0.mlp.fc2.bias 	 Loaded
audio_branch.layers.3.blocks.1.norm1.weight 	 Loaded
audio_branch.layers.3.blocks.1.norm1.bias 	 Loaded
audio_branch.layers.3.blocks.1.attn.relative_position_bias_table 	 Loaded
audio_branch.layers.3.blocks.1.attn.qkv.weight 	 Loaded
audio_branch.layers.3.blocks.1.attn.qkv.bias 	 Loaded
audio_branch.layers.3.blocks.1.attn.proj.weight 	 Loaded
audio_branch.layers.3.blocks.1.attn.proj.bias 	 Loaded
audio_branch.layers.3.blocks.1.norm2.weight 	 Loaded
audio_branch.layers.3.blocks.1.norm2.bias 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc1.weight 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc1.bias 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc2.weight 	 Loaded
audio_branch.layers.3.blocks.1.mlp.fc2.bias 	 Loaded
audio_branch.norm.weight 	 Loaded
audio_branch.norm.bias 	 Loaded
audio_branch.tscam_conv.weight 	 Loaded
audio_branch.tscam_conv.bias 	 Loaded
audio_branch.head.weight 	 Loaded
audio_branch.head.bias 	 Loaded
text_branch.embeddings.word_embeddings.weight 	 Loaded
text_branch.embeddings.position_embeddings.weight 	 Loaded
text_branch.embeddings.token_type_embeddings.weight 	 Loaded
text_branch.embeddings.LayerNorm.weight 	 Loaded
text_branch.embeddings.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.0.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.0.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.0.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.0.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.0.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.0.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.0.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.0.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.0.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.0.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.0.output.dense.weight 	 Loaded
text_branch.encoder.layer.0.output.dense.bias 	 Loaded
text_branch.encoder.layer.0.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.0.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.1.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.1.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.1.attention.output.dense.weight 	 Loaded
text_branch.encoder.layer.1.attention.output.dense.bias 	 Loaded
text_branch.encoder.layer.1.attention.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.1.attention.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.1.intermediate.dense.weight 	 Loaded
text_branch.encoder.layer.1.intermediate.dense.bias 	 Loaded
text_branch.encoder.layer.1.output.dense.weight 	 Loaded
text_branch.encoder.layer.1.output.dense.bias 	 Loaded
text_branch.encoder.layer.1.output.LayerNorm.weight 	 Loaded
text_branch.encoder.layer.1.output.LayerNorm.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.query.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.query.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.key.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.key.bias 	 Loaded
text_branch.encoder.layer.2.attention.self.value.weight 	 Loaded
text_branch.encoder.layer.2.attention.self.value.bias 	 Loaded
text_branch.encoder.layer.2.attention.output.dense.weight 	 Loaded

In [ ]:
import pandas as pd
CLO_dev = "/content/data/Clotho/dev_metadata.csv"
CLOE_dev = "/content/clotho_development_gpt4.csv"
CLO_val = "/content/data/Clotho/val_metadata.csv"
CLOE_val = "/content/clotho_validation_gpt4.csv"
CLO_eval = "/content/data/Clotho/eval_metadata.csv"
CLOE_eval = "/content/clotho_evaluation_gpt4.csv"



df_CLO_dev = pd.read_csv(CLO_dev, encoding='latin1')
df_CLOE_dev = pd.read_csv(CLOE_dev, encoding='latin1')
df_CLO_val = pd.read_csv(CLO_val, encoding='latin1')
df_CLOE_val = pd.read_csv(CLOE_val, encoding='latin1')
df_CLO_eval = pd.read_csv(CLO_eval, encoding='latin1')
df_CLOE_eval = pd.read_csv(CLOE_eval, encoding='latin1')


print("Row number of CLotho development dataset is " + str(len(df_CLO_dev)))
print("Row number of CLotho development caption dataset is " + str(len(df_CLOE_dev)))
print("Row number of CLotho validation dataset is " + str(len(df_CLO_val)))
print("Row number of CLotho validation caption dataset is " + str(len(df_CLOE_val)))
print("Row number of CLotho evaluation dataset is " + str(len(df_CLO_eval)))
print("Row number of CLotho evaluation caption dataset is " + str(len(df_CLOE_eval)))

Row number of CLotho development dataset is 3839
Row number of CLotho development caption dataset is 3839
Row number of CLotho validation dataset is 1045
Row number of CLotho validation caption dataset is 1045
Row number of CLotho evaluation dataset is 1045
Row number of CLotho evaluation caption dataset is 1045

In [ ]:
df_CLOE_dev['Audio file'] = df_CLOE_dev['Audio file'].replace('Ambience Birds.wav', ' Ambience Birds.wav')
df_CLOE_dev['Audio file'] = df_CLOE_dev['Audio file'].replace('typical neighborhood in Porto.wav', ' typical neighborhood in Porto.wav')
df_CLOE_val['Audio file'] = df_CLOE_val['Audio file'].replace('e ieio ieai.wav', ' e ieio ieai.wav')


df_CLO_dev = df_CLO_dev.sort_values(by=['file_name'], ignore_index=True)
df_CLOE_dev = df_CLOE_dev.sort_values(by=['Audio file'], ignore_index=True)
df_CLO_val = df_CLO_val.sort_values(by=['file_name'], ignore_index=True)
df_CLOE_val = df_CLOE_val.sort_values(by=['Audio file'], ignore_index=True)
df_CLO_eval = df_CLO_eval.sort_values(by=['file_name'], ignore_index=True)
df_CLOE_eval = df_CLOE_eval.sort_values(by=['Audio file'], ignore_index=True)


# check for Clotho dataset
Clotho_dev_audio_files = os.listdir("/content/data/Clotho/audio/development")
print(df_CLO_dev["file_name"].isin(Clotho_dev_audio_files).value_counts())

Clotho_val_audio_files = os.listdir("/content/data/Clotho/audio/validation")
print(df_CLO_val["file_name"].isin(Clotho_val_audio_files).value_counts())

Clotho_eval_audio_files = os.listdir("/content/data/Clotho/audio/evaluation")
print(df_CLO_eval["file_name"].isin(Clotho_eval_audio_files).value_counts())
# The upper result shows that the file name from caption csv in Clotho dataset is exactly the same with audio file name


print("=========Start to check for CLOE===========")
# check for CLOE data set
Clotho_dev_audio_files = os.listdir("/content/data/Clotho/audio/development")
print(df_CLOE_dev["Audio file"].isin(Clotho_dev_audio_files).value_counts())

Clotho_val_audio_files = os.listdir("/content/data/Clotho/audio/validation")
print(df_CLOE_val["Audio file"].isin(Clotho_val_audio_files).value_counts())

Clotho_eval_audio_files = os.listdir("/content/data/Clotho/audio/evaluation")
print(df_CLOE_eval["Audio file"].isin(Clotho_eval_audio_files).value_counts())
# The result shows that some of the file names are not aligned

print("=========Start to check for CLOE and CLO relationship===========")
print((df_CLOE_dev["Audio file"] == df_CLO_dev["file_name"]).value_counts())
a = df_CLOE_dev[(df_CLOE_dev["Audio file"] != df_CLO_dev["file_name"])]["Audio file"]
b = df_CLO_dev[(df_CLOE_dev["Audio file"] != df_CLO_dev["file_name"])]["file_name"]

#print("We can find here the difference is the space in the start of file name in CLOE dataset ")
#print("We can also find the data order of CLO and CLOE is aligned!")
#print("Same for valid and eval data")


# print((df_CLOE_val["Audio file"] == df_CLO_val["file_name"]).value_counts())
# print((df_CLOE_eval["Audio file"] == df_CLO_eval["file_name"]).value_counts())

file_name
True    3839
Name: count, dtype: int64
file_name
True    1045
Name: count, dtype: int64
file_name
True    1045
Name: count, dtype: int64
=========Start to check for CLOE===========
Audio file
True    3839
Name: count, dtype: int64
Audio file
True    1045
Name: count, dtype: int64
Audio file
True    1045
Name: count, dtype: int64
=========Start to check for CLOE and CLO relationship===========
True    3839
Name: count, dtype: int64

In [ ]:
import torch
import laion_clap
import numpy as np
from pathlib import Path
from tqdm import tqdm

def get_clap_embeddings_batch_clap22(
    audio_paths,
    batch_size=32,
    device='cuda' if torch.cuda.is_available() else 'cpu'
):
    """
    Generate CLAP embeddings for multiple audio files in batches
    """
    clap_model = CLAP(version = '2022', use_cuda=False)

    all_embeddings = []

    # Process in batches
    for i in tqdm(range(0, len(audio_paths), batch_size)):
        batch_paths = audio_paths[i:i + batch_size]
        embeddings = clap_model.get_audio_embeddings(batch_paths)
        all_embeddings.append(embeddings)

    return all_embeddings

def get_clap_embeddings_batch_laion(
    audio_paths,
    batch_size=32,
    device='cuda' if torch.cuda.is_available() else 'cpu'
):
    """
    Generate CLAP embeddings for multiple audio files in batches
    """
    laion_model = laion_clap.CLAP_Module(enable_fusion=False, device=device)

    all_embeddings = []

    # Process in batches
    for i in tqdm(range(0, len(audio_paths), batch_size)):
        batch_paths = audio_paths[i:i + batch_size]
        embeddings = laion_model.get_audio_embedding_from_filelist(batch_paths)
        all_embeddings.append(embeddings)

    return all_embeddings


if __name__ == "__main__":

    audio_dir = "/content/data/Clotho/audio/development"
    audio_paths = list(Path(audio_dir).glob("*.wav"))

    # Get embeddings
    audio_embeddings = get_clap_embeddings_batch_clap22(audio_paths)
    for i in range(len(audio_embeddings)):
      audio_embeddings[i] = torch.tensor(audio_embeddings[i])
    audio_embeddings = torch.cat(audio_embeddings, dim=0)
    # Save embeddings
    torch.save(audio_embeddings, '/content/data/dev_audio_embeddings_clap22')
    print(f"Saved embeddings with shape: {audio_embeddings.shape}")

    # Get embeddings
    audio_embeddings = get_clap_embeddings_batch_laion(audio_paths)
    for i in range(len(audio_embeddings)):
      audio_embeddings[i] = torch.tensor(audio_embeddings[i])
    audio_embeddings = torch.cat(audio_embeddings, dim=0)
    # Save embeddings
    torch.save(audio_embeddings, '/content/data/dev_audio_embeddings_laion')
    print(f"Saved embeddings with shape: {audio_embeddings.shape}")

# ================= Evaluation Audio ===================== #
    audio_dir = "/content/data/Clotho/audio/evaluation"
    audio_paths = list(Path(audio_dir).glob("*.wav"))
    # Get embeddings
    audio_embeddings = get_clap_embeddings_batch_clap22(audio_paths)
    for i in range(len(audio_embeddings)):
      audio_embeddings[i] = torch.tensor(audio_embeddings[i])
    audio_embeddings = torch.cat(audio_embeddings, dim=0)
    # Save embeddings
    torch.save(audio_embeddings, '/content/data/eval_audio_embeddings_clap22')
    print(f"Saved embeddings with shape: {audio_embeddings.shape}")
    # Get embeddings
    audio_embeddings = get_clap_embeddings_batch_laion(audio_paths)
    for i in range(len(audio_embeddings)):
      audio_embeddings[i] = torch.tensor(audio_embeddings[i])
    audio_embeddings = torch.cat(audio_embeddings, dim=0)
    # Save embeddings
    torch.save(audio_embeddings, '/content/data/eval_audio_embeddings_laion')
    print(f"Saved embeddings with shape: {audio_embeddings.shape}")


    audio_dir = "/content/data/Clotho/audio/validation"
    audio_paths = list(Path(audio_dir).glob("*.wav"))
    # Get embeddings
    audio_embeddings = get_clap_embeddings_batch_clap22(audio_paths)
    for i in range(len(audio_embeddings)):
      audio_embeddings[i] = torch.tensor(audio_embeddings[i])
    audio_embeddings = torch.cat(audio_embeddings, dim=0)
    # Save embeddings
    torch.save(audio_embeddings, '/content/data/val_audio_embeddings_clap22')
    print(f"Saved embeddings with shape: {audio_embeddings.shape}")
    # Get embeddings
    audio_embeddings = get_clap_embeddings_batch_laion(audio_paths)
    for i in range(len(audio_embeddings)):
      audio_embeddings[i] = torch.tensor(audio_embeddings[i])
    audio_embeddings = torch.cat(audio_embeddings, dim=0)
    # Save embeddings
    torch.save(audio_embeddings, '/content/data/val_audio_embeddings_laion')
    print(f"Saved embeddings with shape: {audio_embeddings.shape}")

100%|██████████| 120/120 [23:04<00:00, 11.54s/it]

Saved embeddings with shape: torch.Size([3839, 1024])

100%|██████████| 120/120 [02:21<00:00,  1.18s/it]

Saved embeddings with shape: torch.Size([3839, 512])

100%|██████████| 33/33 [06:02<00:00, 10.99s/it]

Saved embeddings with shape: torch.Size([1045, 1024])

100%|██████████| 33/33 [00:36<00:00,  1.11s/it]

Saved embeddings with shape: torch.Size([1045, 512])

100%|██████████| 33/33 [05:19<00:00,  9.69s/it]

Saved embeddings with shape: torch.Size([1045, 1024])

100%|██████████| 33/33 [00:36<00:00,  1.12s/it]

Saved embeddings with shape: torch.Size([1045, 512])

In [ ]:
def process_entailment_data(df):
  df_entailment = pd.DataFrame()
  labels = ["Entailment", "Neutral", "Contradiction"]
  for i, label in enumerate(labels):
    if df_entailment is None:
      temp = df[["Audio file", "Caption", label]]
      temp.rename(columns={label: 'Hypothese'}, inplace=True)
      temp["label"] = i
      df_entailment = temp
    else:
      temp = df[["Audio file", "Caption", label]]
      temp.rename(columns={label: 'Hypothese'}, inplace=True)
      temp["label"] = i
      df_entailment = pd.concat([df_entailment, temp], ignore_index = True)
  return df_entailment

def batch_process_text_data_clap22(df, batch_size = 200):
  text_embeddings = []
  total_text = df["Hypothese"].tolist()
  for i in range(0, len(df), batch_size):
    batch = total_text[i:i+batch_size]
    text_embeddings_batch = clap_model.get_text_embeddings(batch)
    text_embeddings.extend(text_embeddings_batch)
    del text_embeddings_batch
  text_embeddings = torch.stack(text_embeddings)
  return text_embeddings

def batch_process_text_data_laion(df, batch_size = 200):
  text_embeddings = []
  total_text = df["Hypothese"].tolist()
  for i in range(0, len(df), batch_size):
    batch = total_text[i:i+batch_size]
    text_embeddings_batch = laion_model.get_text_embedding(batch)
    #text_embeddings.extend(text_embeddings_batch)
    text_embeddings.extend(torch.tensor(embedding) for embedding in text_embeddings_batch)
    del text_embeddings_batch
  text_embeddings = torch.stack(text_embeddings)
  return text_embeddings

In [ ]:
dev_entailment = process_entailment_data(df_CLOE_dev)
dev_text_embedding_clap22 = batch_process_text_data_clap22(dev_entailment)
torch.save(dev_text_embedding_clap22, '/content/data/dev_text_embeddings_clap22')
dev_text_embedding_laion = batch_process_text_data_laion(dev_entailment)
torch.save(dev_text_embedding_laion, '/content/data/dev_text_embeddings_laion')


val_entailment = process_entailment_data(df_CLOE_val)
val_text_embedding_clap22 = batch_process_text_data_clap22(val_entailment)
torch.save(val_text_embedding_clap22, '/content/data/val_text_embeddings_clap22')
val_text_embedding_laion = batch_process_text_data_laion(val_entailment)
torch.save(val_text_embedding_laion, '/content/data/val_text_embeddings_laion')

eval_entailment = process_entailment_data(df_CLOE_eval)
eval_text_embedding_clap22 = batch_process_text_data_clap22(eval_entailment)
torch.save(eval_text_embedding_clap22, '/content/data/eval_text_embeddings_clap22')
eval_text_embedding_laion = batch_process_text_data_laion(eval_entailment)
torch.save(eval_text_embedding_laion, '/content/data/eval_text_embeddings_laion')

In [ ]:
dev_label = torch.tensor(dev_entailment["label"].tolist())
val_label = torch.tensor(val_entailment["label"].tolist())
eval_label = torch.tensor(eval_entailment["label"].tolist())

torch.save(dev_label, '/content/data/dev_label')
torch.save(val_label, '/content/data/val_label')
torch.save(eval_label, '/content/data/eval_label')

In [ ]:
!pip install torchsummaryX==1.1.0 wandb --quiet

In [ ]:
import torch
import numpy as np
from torchsummaryX import summary
import sklearn
import gc
import zipfile
import pandas as pd
from tqdm.auto import tqdm
import os
import datetime
import wandb
from torch.optim import lr_scheduler
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Device: ", device)

Device:  cuda

In [ ]:
dev_audio = []
for path in ["/content/data/dev_audio_embeddings_clap22", "/content/data/dev_audio_embeddings_laion"]:
  dev_audio_model = torch.load(path, weights_only=True)
  dev_audio_model = dev_audio_model.repeat(3,1)
  dev_audio.append(dev_audio_model)
dev_text = []
for path in ["/content/data/dev_text_embeddings_clap22", "/content/data/dev_text_embeddings_laion"]:
  dev_text_model = torch.load(path, weights_only=True)
  dev_text.append(dev_text_model)
dev_label = torch.load("/content/data/dev_label", weights_only=True)


val_audio = []
for path in ["/content/data/val_audio_embeddings_clap22", "/content/data/val_audio_embeddings_laion"]:
  val_audio_model = torch.load(path, weights_only=True)
  val_audio_model = val_audio_model.repeat(3,1)
  val_audio.append(val_audio_model)
val_text = []
for path in ["/content/data/val_text_embeddings_clap22", "/content/data/val_text_embeddings_laion"]:
  val_text_model = torch.load(path, weights_only=True)
  val_text.append(val_text_model)
val_label = torch.load("/content/data/val_label", weights_only=True)

eval_audio = []
for path in ["/content/data/eval_audio_embeddings_clap22", "/content/data/eval_audio_embeddings_laion"]:
  eval_audio_model = torch.load(path, weights_only=True)
  eval_audio_model = eval_audio_model.repeat(3,1)
  eval_audio.append(eval_audio_model)
eval_text = []
for path in ["/content/data/eval_text_embeddings_clap22", "/content/data/eval_text_embeddings_laion"]:
  eval_text_model = torch.load(path, weights_only=True)
  eval_text.append(eval_text_model)
eval_label = torch.load("/content/data/eval_label", weights_only=True)

In [ ]:
for i in range(len(dev_audio)):
  print("The shape of dev aduio is: ", dev_audio[i].shape)
  print("The shape of dev text is: ", dev_text[i].shape)
  print("The shape of val aduio is: ", val_audio[i].shape)
  print("The shape of val text is: ", val_text[i].shape)
  print("The shape of eval aduio is: ", eval_audio[i].shape)
  print("The shape of eval text is: ", eval_text[i].shape)

print("The shape of dev label is: ", dev_label.shape)
print("The shape of val label is: ", val_label.shape)
print("The shape of eval label is: ", eval_label.shape)

The shape of dev aduio is:  torch.Size([11517, 1024])
The shape of dev text is:  torch.Size([11517, 1024])
The shape of val aduio is:  torch.Size([3135, 1024])
The shape of val text is:  torch.Size([3135, 1024])
The shape of eval aduio is:  torch.Size([3135, 1024])
The shape of eval text is:  torch.Size([3135, 1024])
The shape of dev aduio is:  torch.Size([11517, 512])
The shape of dev text is:  torch.Size([11517, 512])
The shape of val aduio is:  torch.Size([3135, 512])
The shape of val text is:  torch.Size([3135, 512])
The shape of eval aduio is:  torch.Size([3135, 512])
The shape of eval text is:  torch.Size([3135, 512])
The shape of dev label is:  torch.Size([11517])
The shape of val label is:  torch.Size([3135])
The shape of eval label is:  torch.Size([3135])

In [ ]:
print(dev_audio[0][0].shape)

torch.Size([1024])

Debugging

In [ ]:
dev_audio = torch.load("/content/data/dev_audio_embeddings", weights_only=True)
dev_audio = dev_audio.repeat(3,1)
dev_text = torch.load("/content/data/dev_text_embeddings", weights_only=True)
dev_label = torch.load("/content/data/dev_label", weights_only=True)

val_audio = torch.load("/content/data/val_audio_embeddings", weights_only=True)
val_audio = val_audio.repeat(3,1)
val_text = torch.load("/content/data/val_text_embeddings", weights_only=True)
val_label = torch.load("/content/data/val_label", weights_only=True)

eval_audio = torch.load("/content/data/eval_audio_embeddings", weights_only=True)
eval_audio = eval_audio.repeat(3,1)
eval_text = torch.load("/content/data/eval_text_embeddings", weights_only=True)
eval_label = torch.load("/content/data/eval_label", weights_only=True)

print("The shape of dev aduio is: ", dev_audio.shape)
print("The shape of dev text is: ", dev_text.shape)
print("The shape of dev label is: ", dev_label.shape)

print("The shape of val aduio is: ", val_audio.shape)
print("The shape of val text is: ", val_text.shape)
print("The shape of val label is: ", val_label.shape)

print("The shape of eval aduio is: ", eval_audio.shape)
print("The shape of eval text is: ", eval_text.shape)
print("The shape of eval label is: ", eval_label.shape)

The shape of dev aduio is:  torch.Size([11517, 512])
The shape of dev text is:  torch.Size([11517, 512])
The shape of dev label is:  torch.Size([11517])
The shape of val aduio is:  torch.Size([3135, 512])
The shape of val text is:  torch.Size([3135, 512])
The shape of val label is:  torch.Size([3135])
The shape of eval aduio is:  torch.Size([3135, 512])
The shape of eval text is:  torch.Size([3135, 512])
The shape of eval label is:  torch.Size([3135])

In [ ]:
config = {
    'epochs'        : 50,
    'batch_size'    : 32,
    'init_lr'       : 1e-3,
    "weight_decay": 1e-5,
    "drop_out": 0.1
    # Add more as you need them - e.g dropout values, weight decay, scheduler parameters
}

In [ ]:
class Embedding_Dataset(torch.utils.data.Dataset):
  def __init__(self, audio, text, label):
    self.audio = audio
    self.text = text
    self.label = label
  def __len__(self):
    return len(self.label)
  def __getitem__(self, idx):
    return self.audio[idx], self.text[idx], self.label[idx]

In [ ]:
# train_dataset = Embedding_Dataset(dev_audio, dev_text, dev_label)
# test_dataset = Embedding_Dataset(test_audio, test_text, test_label)

dev_dataset = Embedding_Dataset(dev_audio, dev_text, dev_label)
val_dataset = Embedding_Dataset(val_audio, val_text, val_label)
eval_dataset = Embedding_Dataset(eval_audio, eval_text, eval_label)


dev_dataloader = torch.utils.data.DataLoader(dev_dataset, batch_size=config['batch_size'], shuffle=True, num_workers=8, pin_memory=True)
val_dataloader = torch.utils.data.DataLoader(val_dataset, batch_size=config['batch_size'], shuffle=False, num_workers=2, pin_memory=True)
eval_dataloader = torch.utils.data.DataLoader(eval_dataset, batch_size=config['batch_size'], shuffle=False, num_workers=2, pin_memory=True)

print("Batch size     : ", config['batch_size'])
print("Train dataset samples = {}, batches = {}".format(dev_dataset.__len__(), len(dev_dataloader)))
print("Validation dataset samples = {}, batches = {}".format(val_dataset.__len__(), len(val_dataloader)))
print("Evaluation dataset samples = {}, batches = {}".format(eval_dataset.__len__(), len(eval_dataloader)))

Batch size     :  32
Train dataset samples = 11517, batches = 360
Validation dataset samples = 3135, batches = 98
Evaluation dataset samples = 3135, batches = 98

In [ ]:
# test code
for i,j,k in dev_dataloader:
  print(i.shape)
  print(j.shape)
  print(k.shape)
  break

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
ModuleNotFoundError: No module named 'torch.nested._internal'
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
Traceback (most recent call last):
Traceback (most recent call last):
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
ModuleNotFoundError: No module named 'torch.nested._internal'
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
ModuleNotFoundError: No module named 'torch.nested._internal'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
ModuleNotFoundError: No module named 'torch.nested._internal'
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 296, in reduce_tensor
    handle,
ModuleNotFoundError: No module named 'torch.nested._internal'
ModuleNotFoundError: No module named 'torch.nested._internal'
ModuleNotFoundError: No module named 'torch.nested._internal'

KeyboardInterrupt:

In [ ]:
# Baseline
class Baseline_network(torch.nn.Module):

    def __init__(self, input_size, output_size):

        super(Baseline_network, self).__init__()

        self.fc1 = torch.nn.Linear(input_size, output_size)
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        return x

In [ ]:
INPUT_SIZE  = 3072
OUTPUT_SIZE = 3
model = Baseline_network(INPUT_SIZE, OUTPUT_SIZE)
summary(model, torch.zeros(1, INPUT_SIZE))
model = model.to(device)

----------------------------------------------------------------------------------------------------
Layer                   Kernel Shape         Output Shape         # Params (K)      # Mult-Adds (M)
====================================================================================================
0_Linear                   [3072, 3]               [1, 3]                 9.22                 0.01
1_ReLU                             -               [1, 3]                    -                    -
====================================================================================================
# Params:    9.22K
# Mult-Adds: 0.01M
----------------------------------------------------------------------------------------------------

In [ ]:
criterion = torch.nn.CrossEntropyLoss() # Defining Loss function.
# We use CE because the task is multi-class classification

optimizer = torch.optim.Adam(model.parameters(), lr= config['init_lr'], weight_decay = config["weight_decay"]) #Defining Optimizer
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, config["epochs"])

In [ ]:
torch.cuda.empty_cache()
gc.collect()

700

In [ ]:
def train(model, dataloader, optimizer, criterion):

    model.train()
    tloss, tacc = 0, 0 # Monitoring loss and accuracy
    batch_bar   = tqdm(total=len(dataloader), dynamic_ncols=True, leave=False, position=0, desc='Train')

    for i, (audio_clap22, text_clap22, audio_laion, text_laion, label) in enumerate(dataloader):

        ### Initialize Gradients
        optimizer.zero_grad()

        ### Move Data to Device (Ideally GPU)
        audio_clap22 = audio_clap22.to(device)
        text_clap22 = text_clap22.to(device)
        audio_laion = audio_laion.to(device)
        text_laion = text_laion.to(device)
        label = label.to(device)

        #audio_combined = torch.cat(audio_, dim=1)
        #text_combined = torch.cat(text, dim=1)

        concat = torch.cat((audio_clap22, text_clap22, audio_laion, text_laion), dim=1)
        ### Forward Propagation
        logits  = model(concat)

        ### Loss Calculation
        loss    = criterion(logits, label)

        ### Backward Propagation
        loss.backward()

        ### Gradient Descent
        optimizer.step()

        tloss   += loss.item()
        tacc    += torch.sum(torch.argmax(logits, dim= 1) == label).item()/logits.shape[0]

        batch_bar.set_postfix(loss="{:.04f}".format(float(tloss / (i + 1))),
                              acc="{:.04f}%".format(float(tacc*100 / (i + 1))))
        batch_bar.update()

        ### Release memory
        del audio, text, label, concat, logits
        torch.cuda.empty_cache()

    batch_bar.close()
    tloss   /= len(dataloader)
    tacc    /= len(dataloader)

    return tloss, tacc

In [ ]:
def eval(model, dataloader, criterion):

    model.eval() # set model in evaluation mode
    vloss, vacc = 0, 0 # Monitoring loss and accuracy
    batch_bar   = tqdm(total=len(dataloader), dynamic_ncols=True, position=0, leave=False, desc='Val')

    for i, (audio_clap22, text_clap22, audio_laion, text_laion, label) in enumerate(dataloader):

        ### Move data to device (ideally GPU)
        audio_clap22 = audio_clap22.to(device)
        text_clap22 = text_clap22.to(device)
        audio_laion = audio_laion.to(device)
        text_laion = text_laion.to(device)
        label = label.to(device)

        #audio_combined = torch.cat(audio, dim=1)
        #text_combined = torch.cat(text, dim=1)
        concat = torch.cat((audio_clap22, text_clap22, audio_laion, text_laion), dim=1)

        # makes sure that there are no gradients computed as we are not training the model now
        with torch.inference_mode():
            ### Forward Propagation
            logits  = model(concat)
            ### Loss Calculation
            loss    = criterion(logits, label)

        vloss   += loss.item()
        vacc    += torch.sum(torch.argmax(logits, dim= 1) == label).item()/logits.shape[0]


        batch_bar.set_postfix(loss="{:.04f}".format(float(vloss / (i + 1))),
                              acc="{:.04f}%".format(float(vacc*100 / (i + 1))))
        batch_bar.update()

        ### Release memory
        del audio, text, label, concat, logits
        torch.cuda.empty_cache()

    batch_bar.close()
    vloss   /= len(dataloader)
    vacc    /= len(dataloader)

    return vloss, vacc

In [ ]:
wandb.login(key="475c9c8426e88bb357c376e9b13946e191b89fc2")

wandb: WARNING Calling wandb.login() after wandb.init() has no effect.

True

In [ ]:
# Create your wandb run
version = "three"
run = wandb.init(
    name    = f"{version}-run-aoa", ### Wandb creates random run names if you skip this field, we recommend you give useful names
    reinit  = True, ### Allows reinitalizing runs when you re-run this cell
    #id     = "y28t31uz", ### Insert specific run id here if you want to resume a previous run
    #resume = "must", ### You need this to resume previous runs, but comment out reinit = True when using this
    project = "ALM_course_project", ### Project should be created in your wandb account
    config  = config ### Wandb Config for your run
)

In [ ]:
from datetime import datetime
import pytz
timezone = pytz.timezone('America/New_York')

In [ ]:
torch.cuda.empty_cache()
gc.collect()
wandb.watch(model, log="all")

for epoch in range(config["epochs"]):

    print("\nEpoch {}/{}".format(epoch+1, config['epochs']))

    curr_lr                 = float(optimizer.param_groups[0]['lr'])
    train_loss, train_acc   = train(model, dev_dataloader, optimizer, criterion)
    val_loss, val_acc       = eval(model, val_dataloader, criterion)

    print("\tTrain Acc {:.04f}%\tTrain Loss {:.04f}\t Learning Rate {:.07f}".format(train_acc*100, train_loss, curr_lr))
    print("\tVal Acc {:.04f}%\tVal Loss {:.04f}".format(val_acc*100, val_loss))

    ### Log metrics at each epoch in your run
    # Optionally, you can log at each batch inside train/eval functions
    # (explore wandb documentation/wandb recitation)
    wandb.log({'train_acc': train_acc*100, 'train_loss': train_loss,
               'val_acc': val_acc*100, 'valid_loss': val_loss, 'lr': curr_lr})

    scheduler.step()

    if val_acc > 0.75:
      current_time = datetime.now(timezone)
      formatted_time = current_time.strftime("%Y%m%d_%H%M")
      MODEL_SAVE_PATH = f"/content/{np.round(val_acc, 3)}_{formatted_time}_{version}.pt"

      torch.save({
        'epochs': config["epochs"],
        "batch_size": config["batch_size"],
        "init_lr": config["init_lr"],
        'model_state_dict': model.state_dict(),
      }, MODEL_SAVE_PATH)
      print(f"Model saved at {MODEL_SAVE_PATH}")

Epoch 1/50

Train:   0%|          | 0/360 [00:00<?, ?it/s]

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    except Exception as e:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    else:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    else:
  File "<ipython-input-68-bf36d20d2890>", line 9, in __getitem__
    return self.audio[idx], self.text[idx], self.label[idx]
IndexError: list index out of range

In [ ]:
def evaluate_model(model, data_loader, device):
    model.eval()  # Set the model to evaluation mode

    all_preds = []
    all_labels = []

    with torch.no_grad():  # Disable gradient calculation
        for (audio, text, label) in data_loader:
            audio = audio.to(device)
            text = text.to(device)
            label = label.to(device)
            concat = torch.cat((audio, text), dim=1)

            # Forward pass
            outputs = model(concat)
            _, preds = torch.max(outputs, 1)  # Get the predicted class indices

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(label.cpu().numpy())

    # Convert lists to numpy arrays for metric calculations
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    # Calculate metrics
    accuracy = accuracy_score(all_labels, all_preds)
    precision = precision_score(all_labels, all_preds, average=None)  # For each class
    recall = recall_score(all_labels, all_preds, average=None)        # For each class
    f1 = f1_score(all_labels, all_preds, average=None)                # For each class

    # Overall metrics
    macro_precision = precision_score(all_labels, all_preds, average='macro')
    macro_recall = recall_score(all_labels, all_preds, average='macro')
    macro_f1 = f1_score(all_labels, all_preds, average='macro')

    # Print results
    print(f'Accuracy: {accuracy:.4f}')
    print('Precision (per class):', precision)
    print('Recall (per class):', recall)
    print('F1 Score (per class):', f1)
    print(f'Macro Precision: {macro_precision:.4f}')
    print(f'Macro Recall: {macro_recall:.4f}')
    print(f'Macro F1 Score: {macro_f1:.4f}')

In [ ]:
evaluate_model(model, eval_dataloader, device)

Accuracy: 0.7279
Precision (per class): [0.70576132 0.71288102 0.7600349 ]
Recall (per class): [0.65645933 0.6937799  0.83349282]
F1 Score (per class): [0.68021815 0.70320078 0.79507074]
Macro Precision: 0.7262
Macro Recall: 0.7279
Macro F1 Score: 0.7262

Improved Architecture

In [ ]:
config = {
    'epochs'        : 50,
    'batch_size'    : 32,
    'init_lr'       : 1e-3,
    "weight_decay": 1e-6,
    "drop_out": 0.2,
    "T_0": 2,
    "T_mult":3
    # Add more as you need them - e.g dropout values, weight decay, scheduler parameters
}

In [ ]:
class Improved_network(torch.nn.Module):

    def __init__(self, input_size, output_size, dropout_prob=0.5):
        super(Improved_network, self).__init__()

        self.fc1 = torch.nn.Linear(input_size, 1024)
        self.fc2 = torch.nn.Linear(1024, 512)
        self.fc3 = torch.nn.Linear(512, output_size)
        self.relu = torch.nn.ReLU()
        self.dropout = torch.nn.Dropout(p=dropout_prob)  # Add dropout with configurable probability

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.dropout(x)  # Apply dropout after first layer

        x = self.fc2(x)
        x = self.relu(x)
        x = self.dropout(x)  # Apply dropout after second layer

        x = self.fc3(x)
        x = self.relu(x)  # Typically, no dropout after the last layer in classification tasks
        return x

In [ ]:
INPUT_SIZE  = 1024
OUTPUT_SIZE = 3
model = Improved_network(INPUT_SIZE, OUTPUT_SIZE)
summary(model, torch.zeros(1, INPUT_SIZE))
model = model.to(device)

----------------------------------------------------------------------------------------------------
Layer                   Kernel Shape         Output Shape         # Params (K)      # Mult-Adds (M)
====================================================================================================
0_Linear                [1024, 1024]            [1, 1024]             1,049.60                 1.05
1_ReLU                             -            [1, 1024]                    -                    -
2_Dropout                          -            [1, 1024]                    -                    -
3_Linear                 [1024, 512]             [1, 512]               524.80                 0.52
4_ReLU                             -             [1, 512]                    -                    -
5_Dropout                          -             [1, 512]                    -                    -
6_Linear                    [512, 3]               [1, 3]                 1.54                 0.00
7_ReLU                             -               [1, 3]                    -                    -
====================================================================================================
# Params:    1,575.94K
# Mult-Adds: 1.57M
----------------------------------------------------------------------------------------------------

In [ ]:
criterion = torch.nn.CrossEntropyLoss() # Defining Loss function.
# We use CE because the task is multi-class classification


optimizer = torch.optim.Adam(model.parameters(), lr= config['init_lr'], weight_decay = config["weight_decay"]) #Defining Optimizer
#scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, config["epochs"])
# Define scheduler
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",                 # Reduce LR when validation loss stops improving
    factor=0.5,                 # Reduce LR by half
    patience=2,                 # Number of epochs with no improvement
    threshold=1e-4,             # Minimum change to consider an improvement
    verbose=True                # Print LR reduction details
)

In [ ]:
torch.cuda.empty_cache()
gc.collect()

2156

In [ ]:
# Create your wandb run
version = "two"
run = wandb.init(
    name    = f"{version}-run-improved", ### Wandb creates random run names if you skip this field, we recommend you give useful names
    reinit  = True, ### Allows reinitalizing runs when you re-run this cell
    #id     = "y28t31uz", ### Insert specific run id here if you want to resume a previous run
    #resume = "must", ### You need this to resume previous runs, but comment out reinit = True when using this
    project = "ALM_course_project", ### Project should be created in your wandb account
    config  = config ### Wandb Config for your run
)

In [ ]:
from datetime import datetime
import pytz
timezone = pytz.timezone('America/New_York')

In [ ]:
torch.cuda.empty_cache()
gc.collect()
wandb.watch(model, log="all")

for epoch in range(config["epochs"]):

    print("\nEpoch {}/{}".format(epoch+1, config['epochs']))

    curr_lr                 = float(optimizer.param_groups[0]['lr'])
    train_loss, train_acc   = train(model, dev_dataloader, optimizer, criterion)
    val_loss, val_acc       = eval(model, val_dataloader, criterion)

    print("\tTrain Acc {:.04f}%\tTrain Loss {:.04f}\t Learning Rate {:.07f}".format(train_acc*100, train_loss, curr_lr))
    print("\tVal Acc {:.04f}%\tVal Loss {:.04f}".format(val_acc*100, val_loss))

    ### Log metrics at each epoch in your run
    # Optionally, you can log at each batch inside train/eval functions
    # (explore wandb documentation/wandb recitation)
    wandb.log({'train_acc': train_acc*100, 'train_loss': train_loss,
               'val_acc': val_acc*100, 'valid_loss': val_loss, 'lr': curr_lr})

    #scheduler.step()
    scheduler.step(train_loss)


    if val_acc > 0.75:
      current_time = datetime.now(timezone)
      formatted_time = current_time.strftime("%Y%m%d_%H%M")
      MODEL_SAVE_PATH = f"/content/{np.round(val_acc, 3)}_{formatted_time}_{version}.pt"

      torch.save({
        'epochs': config["epochs"],
        "batch_size": config["batch_size"],
        "init_lr": config["init_lr"],
        'model_state_dict': model.state_dict(),
      }, MODEL_SAVE_PATH)
      print(f"Model saved at {MODEL_SAVE_PATH}")

/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py:2380: UserWarning: Run (hf38km4j) is finished. The call to `_console_raw_callback` will be ignored. Please make sure that you are using an active run.
  lambda data: self._console_raw_callback("stderr", data),

Epoch 1/50

Train:   0%|          | 0/360 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(

	Train Acc 33.6288%	Train Loss 1.0987	 Learning Rate 0.0010000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 2/50

	Train Acc 33.2094%	Train Loss 1.0987	 Learning Rate 0.0010000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 3/50

	Train Acc 33.5557%	Train Loss 1.0986	 Learning Rate 0.0010000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 4/50

	Train Acc 33.1358%	Train Loss 1.0986	 Learning Rate 0.0010000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 5/50

	Train Acc 33.4246%	Train Loss 1.0986	 Learning Rate 0.0005000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 6/50

	Train Acc 33.6192%	Train Loss 1.0986	 Learning Rate 0.0005000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 7/50

	Train Acc 33.0298%	Train Loss 1.0987	 Learning Rate 0.0005000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 8/50

	Train Acc 33.8605%	Train Loss 1.0986	 Learning Rate 0.0002500
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 9/50

	Train Acc 33.7425%	Train Loss 1.0986	 Learning Rate 0.0002500
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 10/50

	Train Acc 33.5890%	Train Loss 1.0986	 Learning Rate 0.0002500
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 11/50

	Train Acc 32.9768%	Train Loss 1.0987	 Learning Rate 0.0002500
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 12/50

	Train Acc 33.8233%	Train Loss 1.0986	 Learning Rate 0.0001250
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 13/50

	Train Acc 33.3432%	Train Loss 1.0986	 Learning Rate 0.0001250
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 14/50

	Train Acc 33.2998%	Train Loss 1.0986	 Learning Rate 0.0001250
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 15/50

	Train Acc 33.9395%	Train Loss 1.0986	 Learning Rate 0.0000625
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 16/50

	Train Acc 33.5949%	Train Loss 1.0986	 Learning Rate 0.0000625
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 17/50

	Train Acc 33.2729%	Train Loss 1.0987	 Learning Rate 0.0000625
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 18/50

	Train Acc 33.4776%	Train Loss 1.0986	 Learning Rate 0.0000313
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 19/50

	Train Acc 33.0385%	Train Loss 1.0987	 Learning Rate 0.0000313
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 20/50

	Train Acc 34.0679%	Train Loss 1.0986	 Learning Rate 0.0000313
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 21/50

	Train Acc 33.8664%	Train Loss 1.0987	 Learning Rate 0.0000156
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 22/50

	Train Acc 33.6270%	Train Loss 1.0987	 Learning Rate 0.0000156
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 23/50

	Train Acc 33.5411%	Train Loss 1.0986	 Learning Rate 0.0000156
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 24/50

	Train Acc 33.3770%	Train Loss 1.0987	 Learning Rate 0.0000078
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 25/50

	Train Acc 33.5881%	Train Loss 1.0986	 Learning Rate 0.0000078
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 26/50

	Train Acc 33.7946%	Train Loss 1.0986	 Learning Rate 0.0000078
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 27/50

	Train Acc 33.6078%	Train Loss 1.0987	 Learning Rate 0.0000039
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 28/50

	Train Acc 33.1139%	Train Loss 1.0986	 Learning Rate 0.0000039
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 29/50

	Train Acc 33.4040%	Train Loss 1.0987	 Learning Rate 0.0000039
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 30/50

	Train Acc 33.8170%	Train Loss 1.0985	 Learning Rate 0.0000020
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 31/50

	Train Acc 33.0723%	Train Loss 1.0986	 Learning Rate 0.0000020
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 32/50

	Train Acc 32.8311%	Train Loss 1.0987	 Learning Rate 0.0000020
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 33/50

	Train Acc 33.0984%	Train Loss 1.0987	 Learning Rate 0.0000010
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 34/50

	Train Acc 33.4109%	Train Loss 1.0987	 Learning Rate 0.0000010
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 35/50

	Train Acc 33.3232%	Train Loss 1.0986	 Learning Rate 0.0000010
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 36/50

	Train Acc 33.9769%	Train Loss 1.0986	 Learning Rate 0.0000005
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 37/50

	Train Acc 33.6279%	Train Loss 1.0986	 Learning Rate 0.0000005
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 38/50

	Train Acc 33.6818%	Train Loss 1.0986	 Learning Rate 0.0000005
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 39/50

	Train Acc 34.0056%	Train Loss 1.0986	 Learning Rate 0.0000002
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 40/50

	Train Acc 32.7434%	Train Loss 1.0986	 Learning Rate 0.0000002
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 41/50

	Train Acc 33.6776%	Train Loss 1.0986	 Learning Rate 0.0000002
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 42/50

	Train Acc 33.9344%	Train Loss 1.0986	 Learning Rate 0.0000001
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 43/50

	Train Acc 34.0002%	Train Loss 1.0986	 Learning Rate 0.0000001
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 44/50

	Train Acc 33.2902%	Train Loss 1.0986	 Learning Rate 0.0000001
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 45/50

	Train Acc 33.3761%	Train Loss 1.0986	 Learning Rate 0.0000001
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 46/50

	Train Acc 33.8772%	Train Loss 1.0986	 Learning Rate 0.0000001
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 47/50

	Train Acc 33.2815%	Train Loss 1.0986	 Learning Rate 0.0000001
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 48/50

	Train Acc 33.8476%	Train Loss 1.0986	 Learning Rate 0.0000000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 49/50

	Train Acc 33.2355%	Train Loss 1.0987	 Learning Rate 0.0000000
	Val Acc 33.3546%	Val Loss 1.0986

Epoch 50/50

	Train Acc 33.5584%	Train Loss 1.0987	 Learning Rate 0.0000000
	Val Acc 33.3546%	Val Loss 1.0986

In [ ]:
evaluate_model(model, eval_dataloader, device)

Accuracy: 0.7021
Precision (per class): [0.8673913  0.65919629 0.6871832 ]
Recall (per class): [0.38181818 0.81626794 0.90813397]
F1 Score (per class): [0.53023256 0.72937153 0.78235779]
Macro Precision: 0.7379
Macro Recall: 0.7021
Macro F1 Score: 0.6807